/* eslint-disable @typescript-eslint/no-explicit-any */
/* @ts-nocheck */

import DataSource from '../database/models/common/dataSource';
import Entity from '../database/models/common/entity';

function getDataSourceToBeSeed({ entityDataSourceMap, derivedFieldMapping, organizationId, createdBy, updatedBy }) {
  return [
    {
      _id: entityDataSourceMap.disclosure.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.disclosure.entityId,
      name: 'Disclosure',
      description: '',
      code: 'disclosure',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      __v: 0,
      isVisible: true,
      fieldSettings: [
        {
          attributeId: {
            $oid: '6878bd762e47e0703407dede',
          },
          refAttributeId: [],
          label: 'DisclosureNumber',
          isFilterEnable: false,
          isDashboardFilter: true,
          isSortingEnable: false,
          isDisplayEnable: false,
          isDerived: false,
          type: 'text',
        },
        {
          attributeId: {
            $oid: '6878bd762e47e0703407dedf',
          },
          refAttributeId: [],
          label: 'SBU',
          isFilterEnable: false,
          isDashboardFilter: true,
          isSortingEnable: false,
          isDisplayEnable: false,
          isDerived: false,
          type: 'text',
        },
      ],
    },
    {
      _id: entityDataSourceMap.portfolio.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.portfolio.entityId,
      name: 'Portfolio',
      description: '',
      code: 'portfolio',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      __v: 0,
      isVisible: true,
    },
    {
      _id: entityDataSourceMap.sabicip.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.sabicip.entityId,
      name: 'SABICIP',
      description: '',
      code: 'sabicip',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      __v: 0,
      isVisible: true,
    },
    {
      _id: entityDataSourceMap.ctclinsab.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.ctclinsab.entityId,
      name: 'CTCLINSAB',
      description: '',
      code: 'ctclinsab',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      __v: 0,
      isVisible: true,
    },
    {
      _id: entityDataSourceMap.annuities.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.annuities.entityId,
      name: 'Annuities',
      description: '',
      code: 'annuities',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      __v: 0,
      isVisible: true,
    },
    {
      _id: entityDataSourceMap.sabiccontracts.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.sabiccontracts.entityId,
      name: 'SABIC Contracts',
      description: '',
      code: 'sabiccontracts',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      __v: 0,
      isVisible: true,
    },
    {
      _id: entityDataSourceMap.shppcontracts.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.shppcontracts.entityId,
      name: 'SHPP Contracts',
      description: '',
      code: 'shppcontracts',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      __v: 0,
      isVisible: true,
    },
    {
      _id: entityDataSourceMap.ksacontracts.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.ksacontracts.entityId,
      name: 'KSA Contracts',
      description: '',
      code: 'ksacontracts',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      __v: 0,
      isVisible: true,
    },
    {
      _id: entityDataSourceMap.attorneymapping.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.attorneymapping.entityId,
      name: 'Attorney Mapping',
      description: '',
      code: 'attorneymapping',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      __v: 0,
      isVisible: true,
    },
    {
      _id: entityDataSourceMap.agreementtypemapping.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.agreementtypemapping.entityId,
      name: 'Agreement Type Mapping',
      description: '',
      code: 'agreementtypemapping',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      __v: 0,
      isVisible: true,
    },
    {
      _id: entityDataSourceMap.ipanalystdashboard.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.ipanalystdashboard.entityId,
      name: 'IP Analyst Dashboard',
      description: '',
      code: 'ipanalystdashboard',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      __v: 0,
      isVisible: true,
    },
    {
      _id: entityDataSourceMap.shppaccolade.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.shppaccolade.entityId,
      name: 'SHPP Accolade',
      description: '',
      code: 'shppaccolade',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      __v: 0,
      isVisible: true,
    },
    {
      _id: entityDataSourceMap.sabicaccolade.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.sabicaccolade.entityId,
      name: 'SABIC Accolade',
      description: '',
      code: 'sabicaccolade',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      __v: 0,
      isVisible: true,
    },
    {
      _id: entityDataSourceMap.newfilings.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.newfilings.entityId,
      name: 'New Filings',
      description: '',
      code: 'newfilings',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      __v: 0,
      canEditInline: true,
      uniqueAttributeName: ['SBU'],
      isVisible: true,
    },
    {
      _id: entityDataSourceMap.estimates.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.estimates.entityId,
      name: 'Estimates',
      description: '',
      code: 'estimates',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      __v: 0,
      canEditInline: true,
      uniqueAttributeName: ['SBU'],
      isVisible: true,
    },
    {
      _id: entityDataSourceMap.projectsopened.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.projectsopened.entityId,
      name: 'Projects Opened',
      description: '',
      code: 'projectsopened',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: true,
      uniqueAttributeName: ['SBU'],
      __v: 0,
      isVisible: true,
    },
    {
      _id: entityDataSourceMap.monthlyipglobal.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.monthlyipglobal.entityId,
      name: 'Monthly Ip Global',
      description: '',
      code: 'monthlyipglobal',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],
      __v: 0,
      isVisible: true,
    },
    {
      _id: entityDataSourceMap.monthlyipstc.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.monthlyipstc.entityId,
      name: 'Monthly Ip STC',
      description: '',
      code: 'monthlyipstc',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],

      __v: 0,
      isVisible: true,
    },
    {
      _id: entityDataSourceMap.monthlyipstcsbu.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.monthlyipstcsbu.entityId,
      name: 'Monthly Ip STC SBU',
      description: '',
      code: 'monthlyipstcsbu',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],

      __v: 0,
      isVisible: true,
    },
    {
      _id: entityDataSourceMap.supplementalipagreementsfinalagreementtype.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.supplementalipagreementsfinalagreementtype.entityId,
      name: 'Supplemental Ip Agreements Final AgreementType',
      description: '',
      code: 'supplementalipagreementsfinalagreementtype',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],

      __v: 0,
      isVisible: true,
    },
    {
      _id: entityDataSourceMap.supplementalipagreementsothers.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.supplementalipagreementsothers.entityId,
      name: 'Supplemental Ip Agreements Others',
      description: '',
      code: 'supplementalipagreementsothers',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],

      __v: 0,
      isVisible: true,
    },
    {
      _id: entityDataSourceMap.supplementalipbangaloreipgroupcurrentstatus.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.supplementalipbangaloreipgroupcurrentstatus.entityId,
      name: 'Supplemental Ip Bangalore ip group Current Status',
      description: '',
      code: 'supplementalipbangaloreipgroupcurrentstatus',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],

      __v: 0,
      isVisible: true,
    },
    {
      _id: entityDataSourceMap.supplementalipbangaloreipgroupsbu.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.supplementalipbangaloreipgroupsbu.entityId,
      name: 'Supplemental Ip Bangalore ip group sbu',
      description: '',
      code: 'supplementalipbangaloreipgroupsbu',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],

      __v: 0,
      isVisible: true,
    },
    {
      _id: entityDataSourceMap.supplementalipbangaloreipgroupworkscope.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.supplementalipbangaloreipgroupworkscope.entityId,
      name: 'Supplemental Ip Bangalore ip group Workscope',
      description: '',
      code: 'supplementalipbangaloreipgroupworkscope',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],

      __v: 0,
      isVisible: true,
    },
    {
      _id: entityDataSourceMap.supplementalipbangaloreipgroupworkproduct.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.supplementalipbangaloreipgroupworkproduct.entityId,
      name: 'Supplemental Ip Bangalore ip group Work Product',
      description: '',
      code: 'supplementalipbangaloreipgroupworkproduct',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],

      __v: 0,
      isVisible: true,
    },
    {
      _id: entityDataSourceMap.supplementalipaccolademappingsheet.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.supplementalipaccolademappingsheet.entityId,
      name: 'Supplemental Ip Accolade Mapping Sheet',
      description: '',
      code: 'supplementalipaccolademappingsheet',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],

      __v: 0,
      isVisible: true,
    },
    {
      _id: entityDataSourceMap.supplementalippatentvaluecoverageactive.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.supplementalippatentvaluecoverageactive.entityId,
      name: 'Supplemental Ip PATENT VALUE COVERAGE ACTIVE',
      description: '',
      code: 'supplementalippatentvaluecoverageactive',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],

      __v: 0,
      isVisible: true,
    },
    {
      _id: entityDataSourceMap.patentvaluecoveragenew.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.patentvaluecoveragenew.entityId,
      name: 'PATENT VALUE COVERAGE NEW',
      description: '',
      code: 'patentvaluecoveragenew',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],

      __v: 0,
      isVisible: true,
    },
    {
      _id: entityDataSourceMap.supplementalipstrategicreportingclass.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.supplementalipstrategicreportingclass.entityId,
      name: 'Supplemental Ip Strategic Reporting Class',
      description: '',
      code: 'supplementalipstrategicreportingclass',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],

      __v: 0,
      isVisible: true,
    },
    {
      _id: entityDataSourceMap.supplementalipnewcoverage.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.supplementalipnewcoverage.entityId,
      name: 'Supplemental Ip New Coverage',
      description: '',
      code: 'supplementalipnewcoverage',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],

      __v: 0,
      isVisible: true,
    },
    {
      _id: entityDataSourceMap.intermediatemonthlyipcurrentyearnewappfiled.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.intermediatemonthlyipcurrentyearnewappfiled.entityId,
      name: 'Intermediate MonthlyIp Current Year New App Filed',
      description: '',
      code: 'intermediatemonthlyipcurrentyearnewappfiled',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],

      __v: 0,
      isVisible: false,
    },
    {
      _id: entityDataSourceMap.pctcyinvdisclosurescnvtfilingd.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.pctcyinvdisclosurescnvtfilingd.entityId,
      name: 'Intermediate monthly percentage of current year invention disclosures converted to filings numerator d',
      description: '',
      code: 'pctcyinvdisclosurescnvtfilingd',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],

      __v: 0,
      isVisible: false,
    },
    {
      _id: entityDataSourceMap.pctcyinvdisclosurescnvtfilingi.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.pctcyinvdisclosurescnvtfilingi.entityId,
      name: 'Intermediate monthly percentage of current year invention disclosures converted to filings numerator I',
      description: '',
      code: 'pctcyinvdisclosurescnvtfilingi',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],

      __v: 0,
      isVisible: false,
    },
    {
      _id: entityDataSourceMap.pctcyinvdisclosurescnvtfilingt.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.pctcyinvdisclosurescnvtfilingt.entityId,
      name: 'Intermediate monthly percentage of current year invention disclosures converted to filings denominator total',
      description: '',
      code: 'pctcyinvdisclosurescnvtfilingt',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],

      __v: 0,
      isVisible: false,
    },
    {
      _id: entityDataSourceMap.intermediatemonthlyipappsbeingdrafted.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.intermediatemonthlyipappsbeingdrafted.entityId,
      name: 'Intermediate MonthlyIp Apps Being Drafted',
      description: '',
      code: 'intermediatemonthlyipappsbeingdrafted',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],

      __v: 0,
      isVisible: false,
    },
    {
      _id: entityDataSourceMap.monthlyip_projects_opened_cy.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.monthlyip_projects_opened_cy.entityId,
      name: 'Intermediate MonthlyIp Projects Opened In CY',
      description: '',
      code: 'monthlyip_projects_opened_cy',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],

      __v: 0,
      isVisible: false,
    },
    {
      _id: entityDataSourceMap.monthlyip_total_active_projects.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.monthlyip_total_active_projects.entityId,
      name: 'Intermediate MonthlyIp Total Active Projects',
      description: '',
      code: 'monthlyip_total_active_projects',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],

      __v: 0,
      isVisible: false,
    },
    {
      _id: entityDataSourceMap.monthlyip_cy_us_issued.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.monthlyip_cy_us_issued.entityId,
      name: 'Intermediate MonthlyIp CY US Issued',
      description: '',
      code: 'monthlyip_cy_us_issued',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],

      __v: 0,
      isVisible: false,
    },
    {
      _id: entityDataSourceMap.monthlyip_cy_intl_issued.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.monthlyip_cy_intl_issued.entityId,
      name: 'Intermediate MonthlyIp CY Intl Issued',
      description: '',
      code: 'monthlyip_cy_intl_issued',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],

      __v: 0,
      isVisible: false,
    },
    {
      _id: entityDataSourceMap.total_us_apps_pending.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.total_us_apps_pending.entityId,
      name: 'Intermediate MonthlyIp Total US Apps pending',
      description: '',
      code: 'total_us_apps_pending',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],

      __v: 0,
      isVisible: false,
    },
    {
      _id: entityDataSourceMap.total_ep_apps_pending.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.total_ep_apps_pending.entityId,
      name: 'Intermediate MonthlyIp Total EP Apps pending',
      description: '',
      code: 'total_ep_apps_pending',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],

      __v: 0,
      isVisible: false,
    },
    {
      _id: entityDataSourceMap.total_cn_apps_pending.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.total_cn_apps_pending.entityId,
      name: 'Intermediate MonthlyIp Total CN Apps pending',
      description: '',
      code: 'total_cn_apps_pending',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],

      __v: 0,
      isVisible: false,
    },
    {
      _id: entityDataSourceMap.other_country_apps_pending.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.other_country_apps_pending.entityId,
      name: 'Intermediate MonthlyIp Other Country Apps pending',
      description: '',
      code: 'other_country_apps_pending',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],

      __v: 0,
      isVisible: false,
    },
    {
      _id: entityDataSourceMap.total_apps_pending.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.total_apps_pending.entityId,
      name: 'Intermediate MonthlyIp Total Apps pending',
      description: '',
      code: 'total_apps_pending',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],

      __v: 0,
      isVisible: false,
    },
    {
      _id: entityDataSourceMap.total_us_issued.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.total_us_issued.entityId,
      name: 'Intermediate MonthlyIp Total US Issued',
      description: '',
      code: 'total_us_issued',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],

      __v: 0,
      isVisible: false,
    },
    {
      _id: entityDataSourceMap.total_ep_issued.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.total_ep_issued.entityId,
      name: 'Intermediate MonthlyIp Total EP Issued',
      description: '',
      code: 'total_ep_issued',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],

      __v: 0,
      isVisible: false,
    },
    {
      _id: entityDataSourceMap.total_cn_issued.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.total_cn_issued.entityId,
      name: 'Intermediate MonthlyIp Total CN Issued',
      description: '',
      code: 'total_cn_issued',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],

      __v: 0,
      isVisible: false,
    },
    {
      _id: entityDataSourceMap.other_country_issued.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.other_country_issued.entityId,
      name: 'Intermediate MonthlyIp Other Country Issued',
      description: '',
      code: 'other_country_issued',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],

      __v: 0,
      isVisible: false,
    },
    {
      _id: entityDataSourceMap.total_issued.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.total_issued.entityId,
      name: 'Intermediate MonthlyIp Total Issued',
      description: '',
      code: 'total_issued',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],

      __v: 0,
      isVisible: false,
    },
    {
      _id: entityDataSourceMap.cy_renewals_due.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.cy_renewals_due.entityId,
      name: 'Intermediate MonthlyIp CY Renewals Due',
      description: '',
      code: 'cy_renewals_due',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],

      __v: 0,
      isVisible: false,
    },
    {
      _id: entityDataSourceMap.annuity_drop.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.annuity_drop.entityId,
      name: 'Intermediate MonthlyIp Annuity Drop',
      description: '',
      code: 'annuity_drop',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],

      __v: 0,
      isVisible: false,
    },
    {
      _id: entityDataSourceMap.priority_drop.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.priority_drop.entityId,
      name: 'Intermediate MonthlyIp Priority Drop',
      description: '',
      code: 'priority_drop',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],

      __v: 0,
      isVisible: false,
    },
    {
      _id: entityDataSourceMap.pct_drop.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.pct_drop.entityId,
      name: 'Intermediate MonthlyIp Pct Drop',
      description: '',
      code: 'pct_drop',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],

      __v: 0,
      isVisible: false,
    },
    {
      _id: entityDataSourceMap.prosecution_drop.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.prosecution_drop.entityId,
      name: 'Intermediate MonthlyIp Prosecution Drop',
      description: '',
      code: 'prosecution_drop',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],

      __v: 0,
      isVisible: false,
    },
    {
      _id: entityDataSourceMap.cy_annuity_savings.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.cy_annuity_savings.entityId,
      name: 'Current year Annuity Savings from current year reductions',
      description: '',
      code: 'cy_annuity_savings',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],

      __v: 0,
      isVisible: false,
    },
    {
      _id: entityDataSourceMap.ny_annuity_savings.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.ny_annuity_savings.entityId,
      name: 'Next year Annuity Savings from current year reductions',
      description: '',
      code: 'ny_annuity_savings',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],

      __v: 0,
      isVisible: false,
    },
    {
      _id: entityDataSourceMap.prosecution_savings.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.prosecution_savings.entityId,
      name: 'Intermediate MonthlyIp Prosecution Savings',
      description: '',
      code: 'prosecution_savings',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],

      __v: 0,
      isVisible: false,
    },
    {
      _id: entityDataSourceMap.annuities_outstanding.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.annuities_outstanding.entityId,
      name: 'Annuities Outstanding',
      description: '',
      code: 'annuities_outstanding',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],

      __v: 0,
      isVisible: false,
    },
    {
      _id: entityDataSourceMap.case_list.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.case_list.entityId,
      name: 'CaseList',
      description: '',
      code: 'caselists',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeRules: [],
      isVisible: true,
      fieldSettings: [
        {
          attributeId: entityDataSourceMap.case_list.caseNumberAttributeId,
          refAttributeId: [],
          label: 'Case Number',
          isFilterEnable: false,
          isDashboardFilter: true,
          isSortingEnable: true,
          isDisplayEnable: true,
          isDerived: false,
          type: 'text',
          mappedAttributeName: 'CaseNumber',
        },
        {
          attributeId: entityDataSourceMap.case_list.attorneyAttributeId,
          refAttributeId: [],
          label: 'Attorney Name',
          isFilterEnable: true,
          isDashboardFilter: true,
          isSortingEnable: true,
          isDisplayEnable: true,
          isDerived: false,
          type: 'multioption',
          mappedAttributeName: 'Attorney',
        },
        {
          attributeId: entityDataSourceMap.case_list.disclosureAttributeId,
          refAttributeId: [],
          label: 'DisclosureNumber',
          isFilterEnable: false,
          isDashboardFilter: true,
          isSortingEnable: false,
          isDisplayEnable: false,
          isDerived: false,
          type: 'text',
          mappedAttributeName: 'DisclosureNumber',
        },
        {
          attributeId: entityDataSourceMap.case_list.activeSwitchAttributeId,
          refAttributeId: [],
          label: 'ActiveSwitch',
          isFilterEnable: false,
          isDashboardFilter: true,
          isSortingEnable: false,
          isDisplayEnable: false,
          isDerived: false,
          type: 'text',
          mappedAttributeName: 'ActiveSwitch',
        },
        {
          attributeId: entityDataSourceMap.case_list.procedureAgentNameAttributeId,
          refAttributeId: [],
          label: 'ProcedureAgentName',
          isFilterEnable: true,
          isDashboardFilter: true,
          isSortingEnable: true,
          isDisplayEnable: true,
          isDerived: false,
          type: 'multioption',
          mappedAttributeName: 'ProcedureAgentName',
        },
        {
          attributeId: entityDataSourceMap.case_list.localAgentNameAttributeId,
          refAttributeId: [],
          label: 'LocalAgentName',
          isFilterEnable: true,
          isDashboardFilter: true,
          isSortingEnable: true,
          isDisplayEnable: true,
          isDerived: false,
          type: 'multioption',
          mappedAttributeName: 'LocalAgentName',
        },
        {
          attributeId: entityDataSourceMap.case_list.caseTypeAttributeId,
          refAttributeId: [],
          label: 'CaseType',
          isFilterEnable: false,
          isDashboardFilter: true,
          isSortingEnable: false,
          isDisplayEnable: false,
          isDerived: false,
          type: 'text',
          mappedAttributeName: 'CaseType',
        },
        {
          attributeId: entityDataSourceMap.case_list.attorneyAttributeId,
          refAttributeId: [
            entityDataSourceMap.ip_counsel.attorneyNameAttributeId,
            entityDataSourceMap.attorney_fo_mapping.foNameAttributeId,
            entityDataSourceMap.formality_officers.foEmailAttributeId,
          ],
          label: 'FO Email',
          isFilterEnable: false,
          isDashboardFilter: true,
          isSortingEnable: false,
          isDisplayEnable: false,
          isDerived: false,
          type: 'email',
          mappedAttributeName: 'Attorney.AttorneyName.FOName.FOEmail',
        },
        {
          attributeId: entityDataSourceMap.case_list.attorneyAttributeId,
          refAttributeId: [
            entityDataSourceMap.ip_counsel.attorneyNameAttributeId,
            entityDataSourceMap.attorney_fo_mapping.foNameAttributeId,
            entityDataSourceMap.formality_officers.escalation1EmailIDAttributeId,
          ],
          label: 'FO Escalation 1 Email',
          isFilterEnable: false,
          isDashboardFilter: true,
          isSortingEnable: false,
          isDisplayEnable: false,
          isDerived: false,
          type: 'email',
          mappedAttributeName: 'Attorney.AttorneyName.FOName.Escalation1EmailID',
        },
        {
          attributeId: entityDataSourceMap.case_list.attorneyAttributeId,
          refAttributeId: [
            entityDataSourceMap.ip_counsel.attorneyNameAttributeId,
            entityDataSourceMap.attorney_fo_mapping.foNameAttributeId,
            entityDataSourceMap.formality_officers.escalation2EmailIDAttributeId,
          ],
          label: 'FO Escalation 2 Email',
          isFilterEnable: false,
          isDashboardFilter: true,
          isSortingEnable: false,
          isDisplayEnable: false,
          isDerived: false,
          type: 'email',
          mappedAttributeName: 'Attorney.AttorneyName.FOName.Escalation2EmailID',
        },
        {
          attributeId: entityDataSourceMap.case_list.actionDueAttributeId,
          refAttributeId: [entityDataSourceMap.action_due.reportCriticalEventAttributeId],
          label: 'ReportCriticalEvent',
          isFilterEnable: false,
          isDashboardFilter: true,
          isSortingEnable: false,
          isDisplayEnable: true,
          isDerived: false,
          type: 'text',
          mappedAttributeName: 'ActionDue.ReportCriticalEvent',
        },
        {
          attributeId: entityDataSourceMap.case_list.actionDueAttributeId,
          refAttributeId: [entityDataSourceMap.action_due.reportPersonalSchedulerAttributeId],
          label: 'ReportPersonalScheduler',
          isFilterEnable: false,
          isDashboardFilter: true,
          isSortingEnable: false,
          isDisplayEnable: true,
          isDerived: false,
          type: 'text',
          mappedAttributeName: 'ActionDue.ReportPersonalScheduler',
        },
        {
          attributeId: entityDataSourceMap.case_list.actionDueAttributeId,
          refAttributeId: [entityDataSourceMap.action_due.reportActionsDueAttributeId],
          label: 'ReportActionDue',
          isFilterEnable: false,
          isDashboardFilter: true,
          isSortingEnable: false,
          isDisplayEnable: true,
          isDerived: false,
          type: 'text',
          mappedAttributeName: 'ActionDue.ReportActionDue',
        },
        {
          attributeId: entityDataSourceMap.case_list.statusAttributeId,
          refAttributeId: [],
          label: 'Status',
          isFilterEnable: false,
          isDashboardFilter: true,
          isSortingEnable: false,
          isDisplayEnable: false,
          isDerived: false,
          type: 'text',
          mappedAttributeName: 'Status',
        },
        {
          attributeId: entityDataSourceMap.case_list.actionDueAttributeId,
          refAttributeId: [],
          label: 'ActionDue',
          isFilterEnable: false,
          isDashboardFilter: true,
          isSortingEnable: false,
          isDisplayEnable: true,
          isDerived: false,
          type: 'option',
          mappedAttributeName: 'ActionDue',
        },
        {
          attributeId: entityDataSourceMap.case_list.dateTakenAttributeId,
          refAttributeId: [],
          label: 'DateTaken',
          isFilterEnable: false,
          isDashboardFilter: true,
          isSortingEnable: false,
          isDisplayEnable: true,
          isDerived: false,
          type: 'date',
          mappedAttributeName: 'DateTaken',
        },
        {
          attributeId: entityDataSourceMap.case_list.countryAttributeId,
          refAttributeId: [],
          label: 'Country',
          isFilterEnable: true,
          isDashboardFilter: true,
          isSortingEnable: false,
          isDisplayEnable: true,
          isDerived: false,
          type: 'multioption',
          mappedAttributeName: 'Country',
        },
        {
          attributeId: entityDataSourceMap.case_list.dueDateAttributeId,
          refAttributeId: [],
          label: 'DueDate',
          isFilterEnable: true,
          isDashboardFilter: true,
          isSortingEnable: false,
          isDisplayEnable: true,
          isDerived: false,
          type: 'date-range',
          mappedAttributeName: 'DueDate',
        },
        {
          attributeId: entityDataSourceMap.case_list.legalAssistantAttributeId,
          refAttributeId: [],
          label: 'legal assistant',
          isFilterEnable: false,
          isDashboardFilter: true,
          isSortingEnable: false,
          isDisplayEnable: true,
          isDerived: false,
          type: 'multioption',
          mappedAttributeName: 'LegalAssistant',
        },
        {
          attributeId: entityDataSourceMap.case_list.actionDueAttributeId,
          refAttributeId: [entityDataSourceMap.action_due.alertRequiredAttributeId],
          label: 'Alert Required',
          isFilterEnable: false,
          isDashboardFilter: true,
          isSortingEnable: false,
          isDisplayEnable: false,
          isDerived: false,
          type: 'text',
        },
        {
          attributeId: entityDataSourceMap.attorney_fo_mapping.foNameAttributeId,
          refAttributeId: [
            entityDataSourceMap.case_list.attorneyAttributeId,
            entityDataSourceMap.ip_counsel.attorneyNameAttributeId,
            entityDataSourceMap.attorney_fo_mapping.foNameAttributeId,
            entityDataSourceMap.formality_officers.foNameAttributeId,
          ],
          label: 'Formality Officer',
          isFilterEnable: false,
          isDashboardFilter: true,
          isSortingEnable: false,
          isDisplayEnable: false,
          isDerived: false,
          type: 'multioption',
          mappedAttributeName: 'Attorney.AttorneyName.FOName.FOName',
        },
        {
          attributeId: derivedFieldMapping.reportCategoryDerivedFieldId,
          refAttributeId: [],
          label: 'Report Category',
          isFilterEnable: true,
          isDashboardFilter: true,
          isSortingEnable: false,
          isDisplayEnable: false,
          isDerived: true,
          type: 'option',
          mappedAttributeName: 'Report Category',
        },
        {
          attributeId: derivedFieldMapping.inHouseDerivedFieldId,
          refAttributeId: [],
          label: 'Handled By',
          isFilterEnable: true,
          isDashboardFilter: true,
          isSortingEnable: false,
          isDisplayEnable: false,
          isDerived: true,
          type: 'option',
          mappedAttributeName: 'Handled By',
        },
        {
          attributeId: derivedFieldMapping.caseListStatusPendingDerivedFieldId,
          refAttributeId: [],
          label: 'Status',
          isFilterEnable: true,
          isDashboardFilter: true,
          isSortingEnable: false,
          isDisplayEnable: false,
          isDerived: true,
          type: 'option',
          mappedAttributeName: 'Case Status',
        },
        {
          attributeId: entityDataSourceMap.case_list.sbuAttributeId,
          refAttributeId: [],
          label: 'SBU',
          isFilterEnable: true,
          isDashboardFilter: true,
          isSortingEnable: false,
          isDisplayEnable: true,
          isDerived: false,
          type: 'multioption',
          mappedAttributeName: 'SBU',
        },
        {
          attributeId: entityDataSourceMap.case_list.actionDueAttributeId,
          refAttributeId: [entityDataSourceMap.action_due.stdActionsAttributeId],
          label: 'Standard Action',
          isFilterEnable: true,
          isDashboardFilter: true,
          isSortingEnable: false,
          isDisplayEnable: true,
          isDerived: false,
          type: 'option',
          mappedAttributeName: 'ActionDue.STDActions',
        },
        {
          attributeId: entityDataSourceMap.case_list.actionDueAttributeId,
          refAttributeId: [entityDataSourceMap.action_due.actionCategoryAttributeId],
          label: 'Action Category',
          isFilterEnable: true,
          isDashboardFilter: true,
          isSortingEnable: false,
          isDisplayEnable: true,
          isDerived: false,
          type: 'option',
          mappedAttributeName: 'ActionDue.ActionCategory',
        },
      ],
      isShowMenu: true,
      updatedBy,
      condition: [
        {
          field: 'ActionDue.Excluded',
          operator: 'eq',
          value: 'N',
          fieldType: 'text',
        },
      ],
    },
    {
      _id: entityDataSourceMap.action_due.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.action_due.entityId,
      name: 'Action Due',
      description: '',
      code: 'actiondues',
      versionType: 'constant',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeRules: [[entityDataSourceMap.action_due.actionDueAttributeId]],
      isVisible: true,

      fieldSettings: [
        {
          attributeId: entityDataSourceMap.action_due.actionDueAttributeId,
          refAttributeId: [],
          label: 'Action Due',
          isFilterEnable: true,
          isDashboardFilter: true,
          isSortingEnable: true,
          isDisplayEnable: true,
          isDerived: false,
          type: 'text-with-option',
          mappedAttributeName: 'actiondue6',
        },
        {
          attributeId: entityDataSourceMap.action_due.stdActionsAttributeId,
          refAttributeId: [],
          label: 'Standard Action',
          isFilterEnable: true,
          isDashboardFilter: true,
          isSortingEnable: false,
          isDisplayEnable: true,
          isDerived: false,
          type: 'option',
          mappedAttributeName: 'STDActions',
        },
        {
          attributeId: entityDataSourceMap.action_due.actionCategoryAttributeId,
          refAttributeId: [],
          label: 'Action Category',
          isFilterEnable: true,
          isDashboardFilter: true,
          isSortingEnable: false,
          isDisplayEnable: true,
          isDerived: false,
          type: 'option',
          mappedAttributeName: 'ActionCategory',
        },
        {
          attributeId: entityDataSourceMap.action_due.alertRequiredAttributeId,
          refAttributeId: [],
          label: 'Alert required',
          isFilterEnable: true,
          isDashboardFilter: true,
          isSortingEnable: false,
          isDisplayEnable: true,
          isDerived: false,
          type: 'text',
          mappedAttributeName: 'AlertRequired',
        },
      ],
      isShowMenu: true,
      updatedBy,
    },
    {
      _id: entityDataSourceMap.ip_counsel.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.ip_counsel.entityId,
      name: 'IP Counsels',
      description: 'IP Counsels',
      code: 'ipcounsels',
      versionType: 'constant',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeRules: [[entityDataSourceMap.ip_counsel.attorneyNameAttributeId]],
      isVisible: true,
      fieldSettings: [
        {
          attributeId: entityDataSourceMap.ip_counsel.attorneyNameAttributeId,
          refAttributeId: [],
          label: 'Attorney Name',
          isFilterEnable: true,
          isDashboardFilter: true,
          isSortingEnable: true,
          isDisplayEnable: true,
          isDerived: false,
          type: 'text-with-option',
          mappedAttributeName: 'AttorneyName',
        },
        {
          attributeId: entityDataSourceMap.formality_officers.foNameAttributeId,
          refAttributeId: [
            entityDataSourceMap.ip_counsel.attorneyNameAttributeId,
            entityDataSourceMap.attorney_fo_mapping.foNameAttributeId,
          ],
          label: 'FO Name',
          isFilterEnable: true,
          isDashboardFilter: true,
          isSortingEnable: true,
          isDisplayEnable: true,
          isDerived: false,
          type: 'text-with-option',
          mappedAttributeName: 'AttorneyName.FOName.FOName',
        },
      ],
      isShowMenu: true,
      updatedBy,
    },
    {
      _id: entityDataSourceMap.formality_officers.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.formality_officers.entityId,
      name: 'Formality Officer',
      description: 'Formality Officer',
      code: 'formalityofficers',
      versionType: 'constant',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeRules: [[entityDataSourceMap.formality_officers.foNameAttributeId]],
      isVisible: true,
      fieldSettings: [
        {
          attributeId: entityDataSourceMap.formality_officers.foNameAttributeId,
          refAttributeId: [],
          label: 'Formality Officer',
          isFilterEnable: true,
          isDashboardFilter: true,
          isSortingEnable: false,
          isDisplayEnable: true,
          isDerived: false,
          type: 'text-with-option',
          mappedAttributeName: 'FOName',
        },
        {
          attributeId: entityDataSourceMap.ip_counsel.attorneyNameAttributeId,
          refAttributeId: [
            entityDataSourceMap.formality_officers.foNameAttributeId,
            entityDataSourceMap.attorney_fo_mapping.attorneyNameAttributeId,
          ],
          label: 'Attorney',
          isFilterEnable: true,
          isDashboardFilter: true,
          isSortingEnable: false,
          isDisplayEnable: true,
          isDerived: false,
          type: 'text-with-option',
          mappedAttributeName: 'FOName.AttorneyName.AttorneyName',
        },
        {
          attributeId: entityDataSourceMap.formality_officers.foEmailAttributeId,
          refAttributeId: [],
          label: 'FO Email',
          isFilterEnable: true,
          isDashboardFilter: true,
          isSortingEnable: false,
          isDisplayEnable: true,
          isDerived: false,
          type: 'email',
          mappedAttributeName: 'FOEmail',
        },
      ],
      isShowMenu: true,
      updatedBy,
    },
    {
      _id: entityDataSourceMap.attorney_fo_mapping.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.attorney_fo_mapping.entityId,
      name: 'Attorney FO Mapping',
      description: '',
      code: 'attorneyfomapping',
      versionType: 'constant',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeRules: [
        [
          entityDataSourceMap.attorney_fo_mapping.attorneyNameAttributeId,
          entityDataSourceMap.attorney_fo_mapping.foNameAttributeId,
        ],
      ],
      isVisible: true,
      fieldSettings: [
        {
          attributeId: entityDataSourceMap.attorney_fo_mapping.attorneyNameAttributeId,
          refAttributeId: [],
          label: 'Attorney',
          isFilterEnable: false,
          isDashboardFilter: true,
          isSortingEnable: false,
          isDisplayEnable: true,
          isDerived: false,
          type: 'multioption',
        },
        {
          attributeId: entityDataSourceMap.attorney_fo_mapping.foNameAttributeId,
          refAttributeId: [],
          label: 'FO Name',
          isFilterEnable: false,
          isDashboardFilter: true,
          isSortingEnable: false,
          isDisplayEnable: true,
          isDerived: false,
          type: 'multioption',
        },
      ],
      isShowMenu: false,
      condition: [],
      updatedBy,
    },
  ];
}
// export async function seedDataSource({ organizationId, createdBy, updatedBy, entityDataSourceMap }) {
//   const dataSources = getDataSourceToBeSeed({
//     entityDataSourceMap,
//     organizationId,
//     createdBy,
//     updatedBy,
//   });

//   for (const dataSource of dataSources) {
//     const existingDataSource = await DataSource.findOne({
//       $or: [{ _id: dataSource._id }, { name: dataSource.name, organizationId: dataSource.organizationId }],
//     });

//     if (!existingDataSource) {
//       const newDataSource = new DataSource(dataSource);
//       await newDataSource.save();
//       console.info(`New data source '${dataSource.name}' created successfully for org ${dataSource.organizationId}.`);
//     } else {
//       console.info(`Data source '${dataSource.name}' already exists for org ${dataSource.organizationId}. Skipping.`);
//     }
//   }
// }

export async function seedDataSource({
  organizationId,
  createdBy,
  updatedBy,
  entityDataSourceMap,
  derivedFieldMapping,
}) {
  const dataSources = getDataSourceToBeSeed({
    entityDataSourceMap,
    organizationId,
    derivedFieldMapping,
    createdBy,
    updatedBy,
  });

  for (const dataSource of dataSources) {
    try {
      let dataSourceWithFieldSetting = dataSource;
      if (
        !['caselists', 'actiondues', 'ipcounsels', 'formalityofficers', 'attorneyfomapping'].includes(
          dataSourceWithFieldSetting.code
        )
      ) {
        const entityDetails = await Entity.findOne({
          _id: dataSource.entityId,
        });

        if (entityDetails && entityDetails.attributes) {
          const fieldSettings = entityDetails.attributes.map((data: any) => {
            return {
              attributeId: data?._id,
              refAttributeId: [],
              label: data.name,
              isFilterEnable: false,
              isDashboardFilter: true,
              isSortingEnable: false,
              isDisplayEnable: false,
              isDerived: false,
              type: data.type,
            };
          });
          if (fieldSettings && fieldSettings.length > 0) {
            dataSourceWithFieldSetting['fieldSettings'] = fieldSettings;
          }
        }
      }

      // Use findByIdAndUpdate with upsert option
      const result = await DataSource.findByIdAndUpdate(
        dataSource._id,
        {
          ...dataSourceWithFieldSetting,
        },
        {
          upsert: true, // Create if doesn't exist
          new: true, // Return the updated document
          runValidators: true, // Run schema validations
        }
      );

      if (result.isNew) {
        console.info(`New data source created with ID: ${dataSource._id}`);
      } else {
        console.info(`Data source updated with ID: ${dataSource._id}`);
      }
    } catch (error) {
      console.error(`Error upserting data source with ID ${dataSource._id}:`, error);
    }
  }
}
