/* eslint-disable @typescript-eslint/no-explicit-any */
/* @ts-nocheck */

import DataSource from '../database/models/common/dataSource';

function getDataSourceToBeSeed({ entityDataSourceMap, organizationId, createdBy, updatedBy }) {
  return [
    {
      _id: entityDataSourceMap.disclosure.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.disclosure.entityId,
      name: 'Disclosure',
      description: '',
      code: 'disclosure',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      __v: 0,
      isVisible: true,
    },
    {
      _id: entityDataSourceMap.portfolio.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.portfolio.entityId,
      name: 'Portfolio',
      description: '',
      code: 'portfolio',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      __v: 0,
      isVisible: true,
    },
    {
      _id: entityDataSourceMap.sabicip.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.sabicip.entityId,
      name: 'SABICIP',
      description: '',
      code: 'sabicip',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      __v: 0,
      isVisible: true,
    },
    {
      _id: entityDataSourceMap.ctclinsab.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.ctclinsab.entityId,
      name: 'CTCLINSAB',
      description: '',
      code: 'ctclinsab',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      __v: 0,
      isVisible: true,
    },
    {
      _id: entityDataSourceMap.annuities.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.annuities.entityId,
      name: 'Annuities',
      description: '',
      code: 'annuities',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      __v: 0,
      isVisible: true,
    },
    {
      _id: entityDataSourceMap.sabiccontracts.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.sabiccontracts.entityId,
      name: 'SABIC Contracts',
      description: '',
      code: 'sabiccontracts',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      __v: 0,
      isVisible: true,
    },
    {
      _id: entityDataSourceMap.shppcontracts.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.shppcontracts.entityId,
      name: 'SHPP Contracts',
      description: '',
      code: 'shppcontracts',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      __v: 0,
      isVisible: true,
    },
    {
      _id: entityDataSourceMap.ksacontracts.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.ksacontracts.entityId,
      name: 'KSA Contracts',
      description: '',
      code: 'ksacontracts',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      __v: 0,
      isVisible: true,
    },
    {
      _id: entityDataSourceMap.attorneymapping.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.attorneymapping.entityId,
      name: 'Attorney Mapping',
      description: '',
      code: 'attorneymapping',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      __v: 0,
      isVisible: true,
    },
    {
      _id: entityDataSourceMap.agreementtypemapping.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.agreementtypemapping.entityId,
      name: 'Agreement Type Mapping',
      description: '',
      code: 'agreementtypemapping',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      __v: 0,
      isVisible: true,
    },
    {
      _id: entityDataSourceMap.ipanalystdashboard.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.ipanalystdashboard.entityId,
      name: 'IP Analyst Dashboard',
      description: '',
      code: 'ipanalystdashboard',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      __v: 0,
      isVisible: true,
    },
    {
      _id: entityDataSourceMap.shppaccolade.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.shppaccolade.entityId,
      name: 'SHPP Accolade',
      description: '',
      code: 'shppaccolade',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      __v: 0,
      isVisible: true,
    },
    {
      _id: entityDataSourceMap.sabicaccolade.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.sabicaccolade.entityId,
      name: 'SABIC Accolade',
      description: '',
      code: 'sabicaccolade',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      __v: 0,
      isVisible: true,
    },
    {
      _id: entityDataSourceMap.newfilings.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.newfilings.entityId,
      name: 'New Filings',
      description: '',
      code: 'newfilings',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      __v: 0,
      canEditInline: true,
      uniqueAttributeName: ['SBU'],
      isVisible: true,
    },
    {
      _id: entityDataSourceMap.estimates.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.estimates.entityId,
      name: 'Estimates',
      description: '',
      code: 'estimates',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      __v: 0,
      canEditInline: true,
      uniqueAttributeName: ['SBU'],
      isVisible: true,
    },
    {
      _id: entityDataSourceMap.projectsopened.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.projectsopened.entityId,
      name: 'Projects Opened',
      description: '',
      code: 'projectsopened',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: true,
      uniqueAttributeName: ['SBU'],
      __v: 0,
      isVisible: true,
    },
    {
      _id: entityDataSourceMap.monthlyipglobal.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.monthlyipglobal.entityId,
      name: 'Monthly Ip Global',
      description: '',
      code: 'monthlyipglobal',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],
      __v: 0,
      isVisible: true,
    },
    {
      _id: entityDataSourceMap.monthlyipstc.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.monthlyipstc.entityId,
      name: 'Monthly Ip STC',
      description: '',
      code: 'monthlyipstc',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],

      __v: 0,
      isVisible: true,
    },
    {
      _id: entityDataSourceMap.monthlyipstcsbu.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.monthlyipstcsbu.entityId,
      name: 'Monthly Ip STC SBU',
      description: '',
      code: 'monthlyipstcsbu',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],

      __v: 0,
      isVisible: true,
    },
    {
      _id: entityDataSourceMap.supplementalipagreementsfinalagreementtype.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.supplementalipagreementsfinalagreementtype.entityId,
      name: 'Supplemental Ip Agreements Final AgreementType',
      description: '',
      code: 'supplementalipagreementsfinalagreementtype',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],

      __v: 0,
      isVisible: true,
    },
    {
      _id: entityDataSourceMap.supplementalipagreementsothers.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.supplementalipagreementsothers.entityId,
      name: 'Supplemental Ip Agreements Others',
      description: '',
      code: 'supplementalipagreementsothers',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],

      __v: 0,
      isVisible: true,
    },
    {
      _id: entityDataSourceMap.supplementalipbangaloreipgroupcurrentstatus.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.supplementalipbangaloreipgroupcurrentstatus.entityId,
      name: 'Supplemental Ip Bangalore ip group Current Status',
      description: '',
      code: 'supplementalipbangaloreipgroupcurrentstatus',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],

      __v: 0,
      isVisible: true,
    },
    {
      _id: entityDataSourceMap.supplementalipbangaloreipgroupsbu.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.supplementalipbangaloreipgroupsbu.entityId,
      name: 'Supplemental Ip Bangalore ip group sbu',
      description: '',
      code: 'supplementalipbangaloreipgroupsbu',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],

      __v: 0,
      isVisible: true,
    },
    {
      _id: entityDataSourceMap.supplementalipbangaloreipgroupworkscope.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.supplementalipbangaloreipgroupworkscope.entityId,
      name: 'Supplemental Ip Bangalore ip group Workscope',
      description: '',
      code: 'supplementalipbangaloreipgroupworkscope',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],

      __v: 0,
      isVisible: true,
    },
    {
      _id: entityDataSourceMap.supplementalipbangaloreipgroupworkproduct.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.supplementalipbangaloreipgroupworkproduct.entityId,
      name: 'Supplemental Ip Bangalore ip group Work Product',
      description: '',
      code: 'supplementalipbangaloreipgroupworkproduct',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],

      __v: 0,
      isVisible: true,
    },
    {
      _id: entityDataSourceMap.supplementalipaccolademappingsheet.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.supplementalipaccolademappingsheet.entityId,
      name: 'Supplemental Ip Accolade Mapping Sheet',
      description: '',
      code: 'supplementalipaccolademappingsheet',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],

      __v: 0,
      isVisible: true,
    },
    {
      _id: entityDataSourceMap.supplementalippatentvaluecoverageactive.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.supplementalippatentvaluecoverageactive.entityId,
      name: 'Supplemental Ip PATENT VALUE COVERAGE ACTIVE',
      description: '',
      code: 'supplementalippatentvaluecoverageactive',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],

      __v: 0,
      isVisible: true,
    },
    {
      _id: entityDataSourceMap.patentvaluecoveragenew.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.patentvaluecoveragenew.entityId,
      name: 'PATENT VALUE COVERAGE NEW',
      description: '',
      code: 'patentvaluecoveragenew',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],

      __v: 0,
      isVisible: true,
    },
    {
      _id: entityDataSourceMap.supplementalipstrategicreportingclass.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.supplementalipstrategicreportingclass.entityId,
      name: 'Supplemental Ip Strategic Reporting Class',
      description: '',
      code: 'supplementalipstrategicreportingclass',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],

      __v: 0,
      isVisible: true,
    },
    {
      _id: entityDataSourceMap.supplementalipnewcoverage.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.supplementalipnewcoverage.entityId,
      name: 'Supplemental Ip New Coverage',
      description: '',
      code: 'supplementalipnewcoverage',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],

      __v: 0,
      isVisible: true,
    },
    {
      _id: entityDataSourceMap.intermediatemonthlyipcurrentyearnewappfiled.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.intermediatemonthlyipcurrentyearnewappfiled.entityId,
      name: 'Intermediate MonthlyIp Current Year New App Filed',
      description: '',
      code: 'intermediatemonthlyipcurrentyearnewappfiled',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],

      __v: 0,
      isVisible: false,
    },
    {
      _id: entityDataSourceMap.pctcyinvdisclosurescnvtfilingd.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.pctcyinvdisclosurescnvtfilingd.entityId,
      name: 'Intermediate monthly percentage of current year invention disclosures converted to filings numerator d',
      description: '',
      code: 'pctcyinvdisclosurescnvtfilingd',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],

      __v: 0,
      isVisible: false,
    },
    {
      _id: entityDataSourceMap.pctcyinvdisclosurescnvtfilingi.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.pctcyinvdisclosurescnvtfilingi.entityId,
      name: 'Intermediate monthly percentage of current year invention disclosures converted to filings numerator I',
      description: '',
      code: 'pctcyinvdisclosurescnvtfilingi',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],

      __v: 0,
      isVisible: false,
    },
    {
      _id: entityDataSourceMap.pctcyinvdisclosurescnvtfilingt.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.pctcyinvdisclosurescnvtfilingt.entityId,
      name: 'Intermediate monthly percentage of current year invention disclosures converted to filings denominator total',
      description: '',
      code: 'pctcyinvdisclosurescnvtfilingt',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],

      __v: 0,
      isVisible: false,
    },
    {
      _id: entityDataSourceMap.intermediatemonthlyipappsbeingdrafted.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.intermediatemonthlyipappsbeingdrafted.entityId,
      name: 'Intermediate MonthlyIp Apps Being Drafted',
      description: '',
      code: 'intermediatemonthlyipappsbeingdrafted',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],

      __v: 0,
      isVisible: false,
    },
    {
      _id: entityDataSourceMap.monthlyip_projects_opened_cy.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.monthlyip_projects_opened_cy.entityId,
      name: 'Intermediate MonthlyIp Projects Opened In CY',
      description: '',
      code: 'monthlyip_projects_opened_cy',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],

      __v: 0,
      isVisible: false,
    },
    {
      _id: entityDataSourceMap.monthlyip_total_active_projects.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.monthlyip_total_active_projects.entityId,
      name: 'Intermediate MonthlyIp Total Active Projects',
      description: '',
      code: 'monthlyip_total_active_projects',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],

      __v: 0,
      isVisible: false,
    },
    {
      _id: entityDataSourceMap.monthlyip_cy_us_issued.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.monthlyip_cy_us_issued.entityId,
      name: 'Intermediate MonthlyIp CY US Issued',
      description: '',
      code: 'monthlyip_cy_us_issued',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],

      __v: 0,
      isVisible: false,
    },
    {
      _id: entityDataSourceMap.monthlyip_cy_intl_issued.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.monthlyip_cy_intl_issued.entityId,
      name: 'Intermediate MonthlyIp CY Intl Issued',
      description: '',
      code: 'monthlyip_cy_intl_issued',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],

      __v: 0,
      isVisible: false,
    },
    {
      _id: entityDataSourceMap.total_us_apps_pending.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.total_us_apps_pending.entityId,
      name: 'Intermediate MonthlyIp Total US Apps pending',
      description: '',
      code: 'total_us_apps_pending',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],

      __v: 0,
      isVisible: false,
    },
    {
      _id: entityDataSourceMap.total_ep_apps_pending.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.total_ep_apps_pending.entityId,
      name: 'Intermediate MonthlyIp Total EP Apps pending',
      description: '',
      code: 'total_ep_apps_pending',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],

      __v: 0,
      isVisible: false,
    },
    {
      _id: entityDataSourceMap.total_cn_apps_pending.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.total_cn_apps_pending.entityId,
      name: 'Intermediate MonthlyIp Total CN Apps pending',
      description: '',
      code: 'total_cn_apps_pending',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],

      __v: 0,
      isVisible: false,
    },
    {
      _id: entityDataSourceMap.other_country_apps_pending.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.other_country_apps_pending.entityId,
      name: 'Intermediate MonthlyIp Other Country Apps pending',
      description: '',
      code: 'other_country_apps_pending',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],

      __v: 0,
      isVisible: false,
    },
    {
      _id: entityDataSourceMap.total_apps_pending.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.total_apps_pending.entityId,
      name: 'Intermediate MonthlyIp Total Apps pending',
      description: '',
      code: 'total_apps_pending',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],

      __v: 0,
      isVisible: false,
    },
    {
      _id: entityDataSourceMap.total_us_issued.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.total_us_issued.entityId,
      name: 'Intermediate MonthlyIp Total US Issued',
      description: '',
      code: 'total_us_issued',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],

      __v: 0,
      isVisible: false,
    },
    {
      _id: entityDataSourceMap.total_ep_issued.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.total_ep_issued.entityId,
      name: 'Intermediate MonthlyIp Total EP Issued',
      description: '',
      code: 'total_ep_issued',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],

      __v: 0,
      isVisible: false,
    },
    {
      _id: entityDataSourceMap.total_cn_issued.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.total_cn_issued.entityId,
      name: 'Intermediate MonthlyIp Total CN Issued',
      description: '',
      code: 'total_cn_issued',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],

      __v: 0,
      isVisible: false,
    },
    {
      _id: entityDataSourceMap.other_country_issued.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.other_country_issued.entityId,
      name: 'Intermediate MonthlyIp Other Country Issued',
      description: '',
      code: 'other_country_issued',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],

      __v: 0,
      isVisible: false,
    },
    {
      _id: entityDataSourceMap.total_issued.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.total_issued.entityId,
      name: 'Intermediate MonthlyIp Total Issued',
      description: '',
      code: 'total_issued',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],

      __v: 0,
      isVisible: false,
    },
    {
      _id: entityDataSourceMap.cy_renewals_due.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.cy_renewals_due.entityId,
      name: 'Intermediate MonthlyIp CY Renewals Due',
      description: '',
      code: 'cy_renewals_due',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],

      __v: 0,
      isVisible: false,
    },
    {
      _id: entityDataSourceMap.annuity_drop.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.annuity_drop.entityId,
      name: 'Intermediate MonthlyIp Annuity Drop',
      description: '',
      code: 'annuity_drop',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],

      __v: 0,
      isVisible: false,
    },
    {
      _id: entityDataSourceMap.priority_drop.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.priority_drop.entityId,
      name: 'Intermediate MonthlyIp Priority Drop',
      description: '',
      code: 'priority_drop',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],

      __v: 0,
      isVisible: false,
    },
    {
      _id: entityDataSourceMap.pct_drop.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.pct_drop.entityId,
      name: 'Intermediate MonthlyIp Pct Drop',
      description: '',
      code: 'pct_drop',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],

      __v: 0,
      isVisible: false,
    },
    {
      _id: entityDataSourceMap.prosecution_drop.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.prosecution_drop.entityId,
      name: 'Intermediate MonthlyIp Prosecution Drop',
      description: '',
      code: 'prosecution_drop',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],

      __v: 0,
      isVisible: false,
    },
    {
      _id: entityDataSourceMap.cy_annuity_savings.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.cy_annuity_savings.entityId,
      name: 'Current year Annuity Savings from current year reductions',
      description: '',
      code: 'cy_annuity_savings',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],

      __v: 0,
      isVisible: false,
    },
    {
      _id: entityDataSourceMap.ny_annuity_savings.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.ny_annuity_savings.entityId,
      name: 'Next year Annuity Savings from current year reductions',
      description: '',
      code: 'ny_annuity_savings',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],

      __v: 0,
      isVisible: false,
    },
    {
      _id: entityDataSourceMap.prosecution_savings.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.prosecution_savings.entityId,
      name: 'Intermediate MonthlyIp Prosecution Savings',
      description: '',
      code: 'prosecution_savings',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],

      __v: 0,
      isVisible: false,
    },
    {
      _id: entityDataSourceMap.annuities_outstanding.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.annuities_outstanding.entityId,
      name: 'Annuities Outstanding',
      description: '',
      code: 'annuities_outstanding',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],

      __v: 0,
      isVisible: false,
    },
    {
      _id: entityDataSourceMap.case_list.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.case_list.entityId,
      name: 'Case List',
      description: '',
      code: 'case_list',
      versionType: 'weekly',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],
      isShowMenu: true,
      __v: 0,
      isVisible: false,
    },
    {
      _id: entityDataSourceMap.action_due.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.action_due.entityId,
      name: 'Action Due',
      description: '',
      code: 'action_due',
      versionType: 'constant',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],
      isShowMenu: true,
      __v: 0,
      isVisible: false,
    },
    {
      _id: entityDataSourceMap.ip_counsel.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.ip_counsel.entityId,
      name: 'IP Counsel',
      description: '',
      code: 'ip_counsel',
      versionType: 'constant',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],
      isShowMenu: true,
      __v: 0,
      isVisible: false,
    },
    {
      _id: entityDataSourceMap.formality_officers.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.formality_officers.entityId,
      name: 'Formality Officers',
      description: '',
      code: 'formality_officers',
      versionType: 'constant',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],
      isShowMenu: true,
      __v: 0,
      isVisible: false,
    },
  ];
}
export async function seedDataSource({ organizationId, createdBy, updatedBy, entityDataSourceMap }) {
  const dataSources = getDataSourceToBeSeed({
    entityDataSourceMap,
    organizationId,
    createdBy,
    updatedBy,
  });

  for (const dataSource of dataSources) {
    // Check if the datasource already exists
    const existingDataSource = await DataSource.findById(dataSource._id);
    if (!existingDataSource) {
      // If it doesn't exist, create a new data source
      const newDataSource = new DataSource(dataSource);

      await newDataSource.save();
      console.info(`New data source with payload ${dataSource} created successfully.`);
    } else {
      console.info(`New data source with datasource id ${dataSource._id} already exists.`);
    }
  }
}
