import DataSource from '../database/models/dataSource';

import mongoose from 'mongoose';

function getDataSourceToBeSeed({ entityDataSourceMap, organizationId, createdBy, updatedBy }) {
  return [
    {
      _id: entityDataSourceMap.disclosure.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.disclosure.entityId,
      name: 'Disclosure',
      description: '',
      code: 'disclosure',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      __v: 0,
      isVisible: true,
    },
    {
      _id: entityDataSourceMap.portfolio.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.portfolio.entityId,
      name: 'Portfolio',
      description: '',
      code: 'portfolio',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      __v: 0,
      isVisible: true,
    },
    {
      _id: entityDataSourceMap.sabicip.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.sabicip.entityId,
      name: 'SABICIP',
      description: '',
      code: 'sabicip',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      __v: 0,
      isVisible: true,
    },
    {
      _id: entityDataSourceMap.ctclinsab.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.ctclinsab.entityId,
      name: 'CTCLINSAB',
      description: '',
      code: 'ctclinsab',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      __v: 0,
      isVisible: true,
    },
    {
      _id: entityDataSourceMap.annuities.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.annuities.entityId,
      name: 'Annuities',
      description: '',
      code: 'annuities',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      __v: 0,
      isVisible: true,
    },
    {
      _id: entityDataSourceMap.sabiccontracts.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.sabiccontracts.entityId,
      name: 'SABIC Contracts',
      description: '',
      code: 'sabiccontracts',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      __v: 0,
      isVisible: true,
    },
    {
      _id: entityDataSourceMap.shppcontracts.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.shppcontracts.entityId,
      name: 'SHPP Contracts',
      description: '',
      code: 'shppcontracts',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      __v: 0,
      isVisible: true,
    },
    {
      _id: entityDataSourceMap.ksacontracts.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.ksacontracts.entityId,
      name: 'KSA Contracts',
      description: '',
      code: 'ksacontracts',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      __v: 0,
      isVisible: true,
    },
    {
      _id: entityDataSourceMap.attorneymapping.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.attorneymapping.entityId,
      name: 'Attorney Mapping',
      description: '',
      code: 'attorneymapping',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      __v: 0,
      isVisible: true,
    },
    {
      _id: entityDataSourceMap.agreementtypemapping.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.agreementtypemapping.entityId,
      name: 'Agreement Type Mapping',
      description: '',
      code: 'agreementtypemapping',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      __v: 0,
      isVisible: true,
    },
    {
      _id: entityDataSourceMap.ipanalystdashboard.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.ipanalystdashboard.entityId,
      name: 'IP Analyst Dashboard',
      description: '',
      code: 'ipanalystdashboard',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      __v: 0,
      isVisible: true,
    },
    {
      _id: entityDataSourceMap.shppaccolade.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.shppaccolade.entityId,
      name: 'SHPP Accolade',
      description: '',
      code: 'shppaccolade',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      __v: 0,
      isVisible: true,
    },
    {
      _id: entityDataSourceMap.sabicaccolade.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.sabicaccolade.entityId,
      name: 'SABIC Accolade',
      description: '',
      code: 'sabicaccolade',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      __v: 0,
      isVisible: true,
    },
    {
      _id: entityDataSourceMap.newfilings.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.newfilings.entityId,
      name: 'New Filings',
      description: '',
      code: 'newfilings',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      __v: 0,
      canEditInline: true,
      uniqueAttributeName: ['SBU'],
      isVisible: true,
    },
    {
      _id: entityDataSourceMap.estimates.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.estimates.entityId,
      name: 'Estimates',
      description: '',
      code: 'estimates',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      __v: 0,
      canEditInline: true,
      uniqueAttributeName: ['SBU'],
      isVisible: true,
    },
    {
      _id: entityDataSourceMap.projectsopened.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.projectsopened.entityId,
      name: 'Projects Opened',
      description: '',
      code: 'projectsopened',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: true,
      uniqueAttributeName: ['SBU'],
      __v: 0,
      isVisible: true,
    },
    {
      _id: entityDataSourceMap.monthlyipglobal.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.monthlyipglobal.entityId,
      name: 'Monthly Ip Global',
      description: '',
      code: 'monthlyipglobal',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],
      __v: 0,
      isVisible: true,
    },
    {
      _id: entityDataSourceMap.monthlyipstc.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.monthlyipstc.entityId,
      name: 'Monthly Ip STC',
      description: '',
      code: 'monthlyipstc',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],

      __v: 0,
      isVisible: true,
    },
    {
      _id: entityDataSourceMap.monthlyipstcsbu.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.monthlyipstcsbu.entityId,
      name: 'Monthly Ip STC SBU',
      description: '',
      code: 'monthlyipstcsbu',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],

      __v: 0,
      isVisible: true,
    },
    {
      _id: entityDataSourceMap.supplementalipagreementsfinalagreementtype.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.supplementalipagreementsfinalagreementtype.entityId,
      name: 'Supplemental Ip Agreements Final AgreementType',
      description: '',
      code: 'supplementalipagreementsfinalagreementtype',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],

      __v: 0,
      isVisible: true,
    },
    {
      _id: entityDataSourceMap.supplementalipagreementsothers.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.supplementalipagreementsothers.entityId,
      name: 'Supplemental Ip Agreements Others',
      description: '',
      code: 'supplementalipagreementsothers',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],

      __v: 0,
      isVisible: true,
    },
    {
      _id: entityDataSourceMap.supplementalipbangaloreipgroupcurrentstatus.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.supplementalipbangaloreipgroupcurrentstatus.entityId,
      name: 'Supplemental Ip Bangalore ip group Current Status',
      description: '',
      code: 'supplementalipbangaloreipgroupcurrentstatus',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],

      __v: 0,
      isVisible: true,
    },
    {
      _id: entityDataSourceMap.supplementalipbangaloreipgroupsbu.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.supplementalipbangaloreipgroupsbu.entityId,
      name: 'Supplemental Ip Bangalore ip group sbu',
      description: '',
      code: 'supplementalipbangaloreipgroupsbu',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],

      __v: 0,
      isVisible: true,
    },
    {
      _id: entityDataSourceMap.supplementalipbangaloreipgroupworkscope.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.supplementalipbangaloreipgroupworkscope.entityId,
      name: 'Supplemental Ip Bangalore ip group Workscope',
      description: '',
      code: 'supplementalipbangaloreipgroupworkscope',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],

      __v: 0,
      isVisible: true,
    },
    {
      _id: entityDataSourceMap.supplementalipbangaloreipgroupworkproduct.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.supplementalipbangaloreipgroupworkproduct.entityId,
      name: 'Supplemental Ip Bangalore ip group Work Product',
      description: '',
      code: 'supplementalipbangaloreipgroupworkproduct',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],

      __v: 0,
      isVisible: true,
    },
    {
      _id: entityDataSourceMap.supplementalipaccolademappingsheet.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.supplementalipaccolademappingsheet.entityId,
      name: 'Supplemental Ip Accolade Mapping Sheet',
      description: '',
      code: 'supplementalipaccolademappingsheet',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],

      __v: 0,
      isVisible: true,
    },
    {
      _id: entityDataSourceMap.supplementalippatentvaluecoverageactive.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.supplementalippatentvaluecoverageactive.entityId,
      name: 'Supplemental Ip PATENT VALUE COVERAGE ACTIVE',
      description: '',
      code: 'supplementalippatentvaluecoverageactive',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],

      __v: 0,
      isVisible: true,
    },
    {
      _id: entityDataSourceMap.patentvaluecoveragenew.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.patentvaluecoveragenew.entityId,
      name: 'PATENT VALUE COVERAGE NEW',
      description: '',
      code: 'patentvaluecoveragenew',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],

      __v: 0,
      isVisible: true,
    },
    {
      _id: entityDataSourceMap.supplementalipstrategicreportingclass.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.supplementalipstrategicreportingclass.entityId,
      name: 'Supplemental Ip Strategic Reporting Class',
      description: '',
      code: 'supplementalipstrategicreportingclass',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],

      __v: 0,
      isVisible: true,
    },
    {
      _id: entityDataSourceMap.supplementalipnewcoverage.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.supplementalipnewcoverage.entityId,
      name: 'Supplemental Ip New Coverage',
      description: '',
      code: 'supplementalipnewcoverage',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],

      __v: 0,
      isVisible: true,
    },
    {
      _id: entityDataSourceMap.intermediatemonthlyipcurrentyearnewappfiled.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.intermediatemonthlyipcurrentyearnewappfiled.entityId,
      name: 'Intermediate MonthlyIp Current Year New App Filed',
      description: '',
      code: 'intermediatemonthlyipcurrentyearnewappfiled',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],

      __v: 0,
      isVisible: false,
    },
    {
      _id: entityDataSourceMap.pctcyinvdisclosurescnvtfilingd.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.pctcyinvdisclosurescnvtfilingd.entityId,
      name: 'Intermediate monthly percentage of current year invention disclosures converted to filings numerator d',
      description: '',
      code: 'pctcyinvdisclosurescnvtfilingd',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],

      __v: 0,
      isVisible: false,
    },
    {
      _id: entityDataSourceMap.pctcyinvdisclosurescnvtfilingi.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.pctcyinvdisclosurescnvtfilingi.entityId,
      name: 'Intermediate monthly percentage of current year invention disclosures converted to filings numerator I',
      description: '',
      code: 'pctcyinvdisclosurescnvtfilingi',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],

      __v: 0,
      isVisible: false,
    },
    {
      _id: entityDataSourceMap.pctcyinvdisclosurescnvtfilingt.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.pctcyinvdisclosurescnvtfilingt.entityId,
      name: 'Intermediate monthly percentage of current year invention disclosures converted to filings denominator total',
      description: '',
      code: 'pctcyinvdisclosurescnvtfilingt',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],

      __v: 0,
      isVisible: false,
    },
    {
      _id: entityDataSourceMap.intermediatemonthlyipappsbeingdrafted.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.intermediatemonthlyipappsbeingdrafted.entityId,
      name: 'Intermediate MonthlyIp Apps Being Drafted',
      description: '',
      code: 'intermediatemonthlyipappsbeingdrafted',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],

      __v: 0,
      isVisible: false,
    },
    {
      _id: entityDataSourceMap.monthlyip_projects_opened_cy.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.monthlyip_projects_opened_cy.entityId,
      name: 'Intermediate MonthlyIp Projects Opened In CY',
      description: '',
      code: 'monthlyip_projects_opened_cy',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],

      __v: 0,
      isVisible: false,
    },
    {
      _id: entityDataSourceMap.monthlyip_total_active_projects.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.monthlyip_total_active_projects.entityId,
      name: 'Intermediate MonthlyIp Total Active Projects',
      description: '',
      code: 'monthlyip_total_active_projects',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],

      __v: 0,
      isVisible: false,
    },
    {
      _id: entityDataSourceMap.monthlyip_cy_us_issued.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.monthlyip_cy_us_issued.entityId,
      name: 'Intermediate MonthlyIp CY US Issued',
      description: '',
      code: 'monthlyip_cy_us_issued',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],

      __v: 0,
      isVisible: false,
    },
    {
      _id: entityDataSourceMap.monthlyip_cy_intl_issued.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.monthlyip_cy_intl_issued.entityId,
      name: 'Intermediate MonthlyIp CY Intl Issued',
      description: '',
      code: 'monthlyip_cy_intl_issued',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],

      __v: 0,
      isVisible: false,
    },
    {
      _id: entityDataSourceMap.total_us_apps_pending.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.total_us_apps_pending.entityId,
      name: 'Intermediate MonthlyIp Total US Apps pending',
      description: '',
      code: 'total_us_apps_pending',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],

      __v: 0,
      isVisible: false,
    },
    {
      _id: entityDataSourceMap.total_ep_apps_pending.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.total_ep_apps_pending.entityId,
      name: 'Intermediate MonthlyIp Total EP Apps pending',
      description: '',
      code: 'total_ep_apps_pending',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],

      __v: 0,
      isVisible: false,
    },
    {
      _id: entityDataSourceMap.total_cn_apps_pending.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.total_cn_apps_pending.entityId,
      name: 'Intermediate MonthlyIp Total CN Apps pending',
      description: '',
      code: 'total_cn_apps_pending',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],

      __v: 0,
      isVisible: false,
    },
    {
      _id: entityDataSourceMap.other_country_apps_pending.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.other_country_apps_pending.entityId,
      name: 'Intermediate MonthlyIp Other Country Apps pending',
      description: '',
      code: 'other_country_apps_pending',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],

      __v: 0,
      isVisible: false,
    },
    {
      _id: entityDataSourceMap.total_apps_pending.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.total_apps_pending.entityId,
      name: 'Intermediate MonthlyIp Total Apps pending',
      description: '',
      code: 'total_apps_pending',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],

      __v: 0,
      isVisible: false,
    },
    {
      _id: entityDataSourceMap.total_us_issued.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.total_us_issued.entityId,
      name: 'Intermediate MonthlyIp Total US Issued',
      description: '',
      code: 'total_us_issued',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],

      __v: 0,
      isVisible: false,
    },
    {
      _id: entityDataSourceMap.total_ep_issued.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.total_ep_issued.entityId,
      name: 'Intermediate MonthlyIp Total EP Issued',
      description: '',
      code: 'total_ep_issued',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],

      __v: 0,
      isVisible: false,
    },
    {
      _id: entityDataSourceMap.total_cn_issued.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.total_cn_issued.entityId,
      name: 'Intermediate MonthlyIp Total CN Issued',
      description: '',
      code: 'total_cn_issued',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],

      __v: 0,
      isVisible: false,
    },
    {
      _id: entityDataSourceMap.other_country_issued.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.other_country_issued.entityId,
      name: 'Intermediate MonthlyIp Other Country Issued',
      description: '',
      code: 'other_country_issued',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],

      __v: 0,
      isVisible: false,
    },
    {
      _id: entityDataSourceMap.total_issued.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.total_issued.entityId,
      name: 'Intermediate MonthlyIp Total Issued',
      description: '',
      code: 'total_issued',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],

      __v: 0,
      isVisible: false,
    },
    {
      _id: entityDataSourceMap.cy_renewals_due.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.cy_renewals_due.entityId,
      name: 'Intermediate MonthlyIp CY Renewals Due',
      description: '',
      code: 'cy_renewals_due',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],

      __v: 0,
      isVisible: false,
    },
    {
      _id: entityDataSourceMap.annuity_drop.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.annuity_drop.entityId,
      name: 'Intermediate MonthlyIp Annuity Drop',
      description: '',
      code: 'annuity_drop',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],

      __v: 0,
      isVisible: false,
    },
    {
      _id: entityDataSourceMap.priority_drop.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.priority_drop.entityId,
      name: 'Intermediate MonthlyIp Priority Drop',
      description: '',
      code: 'priority_drop',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],

      __v: 0,
      isVisible: false,
    },
    {
      _id: entityDataSourceMap.pct_drop.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.pct_drop.entityId,
      name: 'Intermediate MonthlyIp Pct Drop',
      description: '',
      code: 'pct_drop',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],

      __v: 0,
      isVisible: false,
    },
    {
      _id: entityDataSourceMap.prosecution_drop.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.prosecution_drop.entityId,
      name: 'Intermediate MonthlyIp Prosecution Drop',
      description: '',
      code: 'prosecution_drop',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],

      __v: 0,
      isVisible: false,
    },
    {
      _id: entityDataSourceMap.cy_annuity_savings.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.cy_annuity_savings.entityId,
      name: 'Current year Annuity Savings from current year reductions',
      description: '',
      code: 'cy_annuity_savings',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],

      __v: 0,
      isVisible: false,
    },
    {
      _id: entityDataSourceMap.ny_annuity_savings.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.ny_annuity_savings.entityId,
      name: 'Next year Annuity Savings from current year reductions',
      description: '',
      code: 'ny_annuity_savings',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],

      __v: 0,
      isVisible: false,
    },
    {
      _id: entityDataSourceMap.prosecution_savings.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.prosecution_savings.entityId,
      name: 'Intermediate MonthlyIp Prosecution Savings',
      description: '',
      code: 'prosecution_savings',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],

      __v: 0,
      isVisible: false,
    },
    {
      _id: entityDataSourceMap.annuities_outstanding.dataSourceId,
      organizationId,
      entityId: entityDataSourceMap.annuities_outstanding.entityId,
      name: 'Annuities Outstanding',
      description: '',
      code: 'annuities_outstanding',
      versionType: 'monthly',
      isActive: true,
      createdBy,
      canEditInline: false,
      uniqueAttributeName: [],

      __v: 0,
      isVisible: false,
    },
  ];
}
export async function seedDataSource(payload) {
  const dataSourceEntityMapReportivix = {
    disclosure: {
      entityId: new mongoose.Types.ObjectId('679232f9753ceb4945e5b3a5'),
      dataSourceId: new mongoose.Types.ObjectId('6792332a753ceb4945e5b3b8'),
    },
    portfolio: {
      entityId: new mongoose.Types.ObjectId('67923579d31b8f4ea2111464'),
      dataSourceId: new mongoose.Types.ObjectId('67923590d31b8f4ea211147b'),
    },
    sabicip: {
      entityId: new mongoose.Types.ObjectId('67a3225421f5f8dd752ce62f'),
      dataSourceId: new mongoose.Types.ObjectId('67a3226221f5f8dd752ce644'),
    },
    ctclinsab: {
      entityId: new mongoose.Types.ObjectId('67a33c7222cb8a927a85e410'),
      dataSourceId: new mongoose.Types.ObjectId('67a33c7f22cb8a927a85e427'),
    },
    annuities: {
      entityId: new mongoose.Types.ObjectId('67a3428622cb8a927a85e4a4'),
      dataSourceId: new mongoose.Types.ObjectId('67a3429322cb8a927a85e4b9'),
    },
    sabiccontracts: {
      entityId: new mongoose.Types.ObjectId('67b30f0982247f52c59f38c0'),
      dataSourceId: new mongoose.Types.ObjectId('67c6d4eb9fb857c9aaf5319c'),
    },
    shppcontracts: {
      entityId: new mongoose.Types.ObjectId('67b4209ceb71879e5fa1e07e'),
      dataSourceId: new mongoose.Types.ObjectId('67c6d4fd9fb857c9aaf531b1'),
    },
    ksacontracts: {
      entityId: new mongoose.Types.ObjectId('67b4452b67ea5efd4f79e659'),
      dataSourceId: new mongoose.Types.ObjectId('67c6d50e9fb857c9aaf531c6'),
    },
    attorneymapping: {
      entityId: new mongoose.Types.ObjectId('67b4488a67ea5efd4f79e666'),
      dataSourceId: new mongoose.Types.ObjectId('67c6d5279fb857c9aaf531db'),
    },
    agreementtypemapping: {
      entityId: new mongoose.Types.ObjectId('67b448f967ea5efd4f79e671'),
      dataSourceId: new mongoose.Types.ObjectId('67c6d5499fb857c9aaf531f0'),
    },
    ipanalystdashboard: {
      entityId: new mongoose.Types.ObjectId('67b44ba567ea5efd4f79e682'),
      dataSourceId: new mongoose.Types.ObjectId('67c6e4ba44cef11611823e70'),
    },
    shppaccolade: {
      entityId: new mongoose.Types.ObjectId('67c6e13e44cef11611823e28'),
      dataSourceId: new mongoose.Types.ObjectId('67c6e4f144cef11611823e8a'),
    },
    sabicaccolade: {
      entityId: new mongoose.Types.ObjectId('67c6e11744cef11611823e17'),
      dataSourceId: new mongoose.Types.ObjectId('67c6e50a44cef11611823e9e'),
    },
    newfilings: {
      entityId: new mongoose.Types.ObjectId('67d8d993b327f8f92cce5f22'),
      dataSourceId: new mongoose.Types.ObjectId('67d8d9f7b327f8f92cce5f48'),
    },
    estimates: {
      entityId: new mongoose.Types.ObjectId('67d8d9c9b327f8f92cce5f2e'),
      dataSourceId: new mongoose.Types.ObjectId('67d8da0cb327f8f92cce5f5c'),
    },
    projectsopened: {
      entityId: new mongoose.Types.ObjectId('67dac48f7d55c5d9d00417c9'),
      dataSourceId: new mongoose.Types.ObjectId('67dac4b17d55c5d9d00417e5'),
    },
    monthlyipglobal: {
      entityId: new mongoose.Types.ObjectId('67f4da8505b8b2e078bbcbac'),
      dataSourceId: new mongoose.Types.ObjectId('67f4e08505b8b2e078bbcc2a'),
    },
    monthlyipstc: {
      entityId: new mongoose.Types.ObjectId('67f899ee3555d2f356d0743f'),
      dataSourceId: new mongoose.Types.ObjectId('67f89a513555d2f356d07485'),
    },
    monthlyipstcsbu: {
      entityId: new mongoose.Types.ObjectId('680b63c114c2fd3bb0972817'),
      dataSourceId: new mongoose.Types.ObjectId('680b640114c2fd3bb097283f'),
    },
    supplementalipagreementsfinalagreementtype: {
      entityId: new mongoose.Types.ObjectId('680db3102e9c639d271dbf11'),
      dataSourceId: new mongoose.Types.ObjectId('680dbc262e9c639d271dbf9d'),
    },
    supplementalipagreementsothers: {
      entityId: new mongoose.Types.ObjectId('680db438556f85595924ae0d'),
      dataSourceId: new mongoose.Types.ObjectId('680dbc422e9c639d271dbfb2'),
    },
    supplementalipbangaloreipgroupcurrentstatus: {
      entityId: new mongoose.Types.ObjectId('680db5022e9c639d271dbf32'),
      dataSourceId: new mongoose.Types.ObjectId('680dbc582e9c639d271dbfc3'),
    },
    supplementalipbangaloreipgroupsbu: {
      entityId: new mongoose.Types.ObjectId('680db585556f85595924ae0f'),
      dataSourceId: new mongoose.Types.ObjectId('680dbc7b2e9c639d271dbfd4'),
    },
    supplementalipbangaloreipgroupworkscope: {
      entityId: new mongoose.Types.ObjectId('680db5c4556f85595924ae12'),
      dataSourceId: new mongoose.Types.ObjectId('680dbc8d2e9c639d271dbfe5'),
    },
    supplementalipbangaloreipgroupworkproduct: {
      entityId: new mongoose.Types.ObjectId('680db5f4556f85595924ae15'),
      dataSourceId: new mongoose.Types.ObjectId('680dbca42e9c639d271dbff6'),
    },
    supplementalipaccolademappingsheet: {
      entityId: new mongoose.Types.ObjectId('680db92e2e9c639d271dbf45'),
      dataSourceId: new mongoose.Types.ObjectId('680dbcb12e9c639d271dc007'),
    },
    supplementalippatentvaluecoverageactive: {
      entityId: new mongoose.Types.ObjectId('680dba6c2e9c639d271dbf4c'),
      dataSourceId: new mongoose.Types.ObjectId('680dbcc02e9c639d271dc018'),
    },
    patentvaluecoveragenew: {
      entityId: new mongoose.Types.ObjectId('680dbb422e9c639d271dbf63'),
      dataSourceId: new mongoose.Types.ObjectId('680dbccf2e9c639d271dc029'),
    },
    supplementalipstrategicreportingclass: {
      entityId: new mongoose.Types.ObjectId('680dbb982e9c639d271dbf6d'),
      dataSourceId: new mongoose.Types.ObjectId('680dbce12e9c639d271dc03a'),
    },
    supplementalipnewcoverage: {
      entityId: new mongoose.Types.ObjectId('680dbbf12e9c639d271dbf77'),
      dataSourceId: new mongoose.Types.ObjectId('680dbd042e9c639d271dc04b'),
    },
    intermediatemonthlyipcurrentyearnewappfiled: {
      entityId: new mongoose.Types.ObjectId('67923579d31b8f4ea2111464'),
      dataSourceId: new mongoose.Types.ObjectId('683575dcfd604f890f263325'),
    },
    pctcyinvdisclosurescnvtfilingd: {
      entityId: new mongoose.Types.ObjectId('67923579d31b8f4ea2111464'),
      dataSourceId: new mongoose.Types.ObjectId('683e6eae336975e9f711e9fd'),
    },
    pctcyinvdisclosurescnvtfilingi: {
      entityId: new mongoose.Types.ObjectId('679232f9753ceb4945e5b3a5'),
      dataSourceId: new mongoose.Types.ObjectId('683e6ec3336975e9f711ea0f'),
    },
    pctcyinvdisclosurescnvtfilingt: {
      entityId: new mongoose.Types.ObjectId('679232f9753ceb4945e5b3a5'),
      dataSourceId: new mongoose.Types.ObjectId('683e6ed7336975e9f711ea21'),
    },
    intermediatemonthlyipappsbeingdrafted: {
      entityId: new mongoose.Types.ObjectId('679232f9753ceb4945e5b3a5'),
      dataSourceId: new mongoose.Types.ObjectId('683eb1a86deb4721418017ea'),
    },
    monthlyip_projects_opened_cy: {
      entityId: new mongoose.Types.ObjectId('679232f9753ceb4945e5b3a5'),
      dataSourceId: new mongoose.Types.ObjectId('6840fd3e0ef4e301481fb2f1'),
    },
    monthlyip_total_active_projects: {
      entityId: new mongoose.Types.ObjectId('679232f9753ceb4945e5b3a5'),
      dataSourceId: new mongoose.Types.ObjectId('6840fdf20ef4e301481fb33c'),
    },
    monthlyip_cy_us_issued: {
      entityId: new mongoose.Types.ObjectId('67923579d31b8f4ea2111464'),
      dataSourceId: new mongoose.Types.ObjectId('68410d0dc1ac3b9dc12593f2'),
    },
    monthlyip_cy_intl_issued: {
      entityId: new mongoose.Types.ObjectId('67923579d31b8f4ea2111464'),
      dataSourceId: new mongoose.Types.ObjectId('68410d44c1ac3b9dc125943a'),
    },
    total_us_apps_pending: {
      entityId: new mongoose.Types.ObjectId('67923579d31b8f4ea2111464'),
      dataSourceId: new mongoose.Types.ObjectId('6841330e971865be2007836b'),
    },
    total_ep_apps_pending: {
      entityId: new mongoose.Types.ObjectId('67923579d31b8f4ea2111464'),
      dataSourceId: new mongoose.Types.ObjectId('68413345971865be200783a9'),
    },
    total_cn_apps_pending: {
      entityId: new mongoose.Types.ObjectId('67923579d31b8f4ea2111464'),
      dataSourceId: new mongoose.Types.ObjectId('6841337e971865be200783ed'),
    },
    other_country_apps_pending: {
      entityId: new mongoose.Types.ObjectId('67923579d31b8f4ea2111464'),
      dataSourceId: new mongoose.Types.ObjectId('684133ac971865be20078431'),
    },
    total_apps_pending: {
      entityId: new mongoose.Types.ObjectId('67923579d31b8f4ea2111464'),
      dataSourceId: new mongoose.Types.ObjectId('684133e5971865be20078498'),
    },
    total_us_issued: {
      entityId: new mongoose.Types.ObjectId('67923579d31b8f4ea2111464'),
      dataSourceId: new mongoose.Types.ObjectId('6841aa0324ef304e9b6b2c4d'),
    },
    total_ep_issued: {
      entityId: new mongoose.Types.ObjectId('67923579d31b8f4ea2111464'),
      dataSourceId: new mongoose.Types.ObjectId('6841aa4424ef304e9b6b2ca3'),
    },
    total_cn_issued: {
      entityId: new mongoose.Types.ObjectId('67923579d31b8f4ea2111464'),
      dataSourceId: new mongoose.Types.ObjectId('6841aa8224ef304e9b6b2cee'),
    },
    other_country_issued: {
      entityId: new mongoose.Types.ObjectId('67923579d31b8f4ea2111464'),
      dataSourceId: new mongoose.Types.ObjectId('6841aac924ef304e9b6b2d31'),
    },
    total_issued: {
      entityId: new mongoose.Types.ObjectId('67923579d31b8f4ea2111464'),
      dataSourceId: new mongoose.Types.ObjectId('6841ab7224ef304e9b6b2d8d'),
    },
    cy_renewals_due: {
      entityId: new mongoose.Types.ObjectId('6841cdafe5af6490b2f41197'),
      dataSourceId: new mongoose.Types.ObjectId('6841cddee5af6490b2f411d1'),
    },
    annuity_drop: {
      entityId: new mongoose.Types.ObjectId('67923579d31b8f4ea2111464'),
      dataSourceId: new mongoose.Types.ObjectId('6841d6f1c12805aa88cd6204'),
    },
    priority_drop: {
      entityId: new mongoose.Types.ObjectId('67923579d31b8f4ea2111464'),
      dataSourceId: new mongoose.Types.ObjectId('6841d72ac12805aa88cd624d'),
    },
    pct_drop: {
      entityId: new mongoose.Types.ObjectId('67923579d31b8f4ea2111464'),
      dataSourceId: new mongoose.Types.ObjectId('6841d756c12805aa88cd6294'),
    },
    prosecution_drop: {
      entityId: new mongoose.Types.ObjectId('67923579d31b8f4ea2111464'),
      dataSourceId: new mongoose.Types.ObjectId('6841d780c12805aa88cd62da'),
    },
    cy_annuity_savings: {
      entityId: new mongoose.Types.ObjectId('6841e260b47f76d5abdd004a'),
      dataSourceId: new mongoose.Types.ObjectId('6841e2bfb47f76d5abdd00cf'),
    },
    ny_annuity_savings: {
      entityId: new mongoose.Types.ObjectId('6841e260b47f76d5abdd004a'),
      dataSourceId: new mongoose.Types.ObjectId('6841e2e3b47f76d5abdd00f7'),
    },
    prosecution_savings: {
      entityId: new mongoose.Types.ObjectId('684250f2cf88c3e8592aee61'),
      dataSourceId: new mongoose.Types.ObjectId('6842510fcf88c3e8592aee97'),
    },
    annuities_outstanding: {
      entityId: new mongoose.Types.ObjectId('67a3428622cb8a927a85e4a4'),
      dataSourceId: new mongoose.Types.ObjectId('6846791aa0e6c029f6d08bed'),
    },
  };

  const reportivixDataSources = getDataSourceToBeSeed({
    entityDataSourceMap: dataSourceEntityMapReportivix,
    organizationId: payload.reportivixOrganizationId,
    createdBy: payload.reportivixSuperAdminUserId,
    updatedBy: payload.reportivixSuperAdminUserId,
  });

  for (const dataSource of reportivixDataSources) {
    // Check if the datasource already exists
    const existingDataSource = await DataSource.findById(dataSource._id);
    if (!existingDataSource) {
      // If it doesn't exist, create a new data source
      const newDataSource = new DataSource(dataSource);

      await newDataSource.save();
      console.info(`New data source with payload ${dataSource} created successfully.`);
    } else {
      console.info(`New data source with datasource id ${dataSource._id} already exists.`);
    }
  }
}
