/* eslint-disable @typescript-eslint/no-explicit-any */
/* @ts-nocheck */

import Permission from '../database/models/common/permissionModel'; // Your Mongoose model
import { getDynamicPermission } from '../database/services/common/permission.service';
interface PermissionSeed {
  name: string;
  method: string;
  resourceId: string;
  extraOptions?: Record<string, any>;
  resourceType: string;
  resourceCode: string;
  isChangeable: boolean;
  isSuperUser?: boolean;
  organizationId?: string; // 👈 added optional field
}

let permissions: PermissionSeed[] = [
  {
    name: 'List User',
    method: 'GET',
    resourceId: '/common/user/list',
    extraOptions: {},
    resourceType: 'User',
    resourceCode: 'user__list',
    isChangeable: true,
  },
  {
    name: 'Get Current User',
    method: 'GET',
    resourceId: '/common/user/get-current-user',
    extraOptions: {},
    resourceType: 'User',
    isSuperUser: false,
    isChangeable: false,
    resourceCode: 'user__get_current_user',
  },
  {
    name: 'Get User',
    method: 'GET',
    resourceId: '/common/user/:userId',
    resourceType: 'User',
    isSuperUser: false,
    isChangeable: true,
    resourceCode: 'user__get_user',
  },
  {
    name: 'Create User',
    method: 'POST',
    resourceId: '/common/user/create',
    extraOptions: {},
    resourceType: 'User',
    resourceCode: 'user__create',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'Update Current User',
    method: 'PUT',
    resourceId: '/common/user/update-current-user',
    extraOptions: {},
    resourceType: 'User',
    resourceCode: 'user__update_current_user',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'Update Current User Password',
    method: 'PUT',
    resourceId: '/common/user/change-password',
    extraOptions: {},
    resourceType: 'User',
    resourceCode: 'user__change_password',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'Update User',
    method: 'PUT',
    resourceId: '/common/user/update/:userId',
    extraOptions: {},
    resourceType: 'User',
    resourceCode: 'user__update',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'Delete User',
    method: 'DELETE',
    resourceId: '/common/user/delete/:userId',
    extraOptions: {},
    resourceType: 'User',
    resourceCode: 'user__delete',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'List Permission',
    method: 'GET',
    resourceId: '/common/permission/list',
    extraOptions: {},
    resourceType: 'Permission',
    resourceCode: 'permission__list',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'Create Permission',
    method: 'POST',
    resourceId: '/common/permission/create',
    extraOptions: {},
    resourceType: 'Permission',
    resourceCode: 'permission__create',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'Update Permission',
    method: 'PUT',
    resourceId: '/common/permission/update/:permissionId',
    extraOptions: {},
    resourceType: 'Permission',
    resourceCode: 'permission__update',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'Delete Permission',
    method: 'DELETE',
    resourceId: '/common/permission/delete/:permissionId',
    extraOptions: {},
    resourceType: 'Permission',
    resourceCode: 'permission__delete',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'List Role',
    method: 'GET',
    resourceId: '/common/role/list',
    extraOptions: {},
    resourceType: 'Role',
    resourceCode: 'role__list',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'List Role Permission',
    method: 'GET',
    resourceId: '/common/role/:roleId',
    extraOptions: {},
    resourceType: 'Role',
    resourceCode: 'role__permission_list',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'Create Role',
    method: 'POST',
    resourceId: '/common/role/create',
    extraOptions: {},
    resourceType: 'Role',
    resourceCode: 'role__create',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'Update Role',
    method: 'PUT',
    resourceId: '/common/role/update/:roleId',
    extraOptions: {},
    resourceType: 'Role',
    resourceCode: 'role__update',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'Delete Role',
    method: 'DELETE',
    resourceId: '/common/role/delete/:roleId',
    extraOptions: {},
    resourceType: 'Role',
    resourceCode: 'role__delete',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'Product List',
    method: 'GET',
    resourceId: '/common/product/list',
    extraOptions: {},
    resourceType: 'Product',
    resourceCode: 'product__list',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'Create Organization',
    method: 'POST',
    resourceId: '/common/organization/create',
    extraOptions: {},
    resourceType: 'Organization',
    resourceCode: 'organization__create',
    isSuperUser: true,
    isChangeable: true,
  },
  {
    name: 'Update Organization',
    method: 'PUT',
    resourceId: '/common/organization/update/:organizationId',
    extraOptions: {},
    resourceType: 'Organization',
    resourceCode: 'organization__update',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'Delete Organization',
    method: 'DELETE',
    resourceId: '/common/organization/delete/:organizationId',
    extraOptions: {},
    resourceType: 'Organization',
    resourceCode: 'organization__delete',
    isSuperUser: true,
    isChangeable: true,
  },
  {
    name: 'Organization List',
    method: 'GET',
    resourceId: '/common/organization/list',
    extraOptions: {},
    resourceType: 'Organization',
    resourceCode: 'organization__list',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'Get Organization',
    method: 'GET',
    resourceId: '/common/organization/:organizationId',
    extraOptions: {},
    resourceType: 'Organization',
    resourceCode: 'organization__get',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'Get Current Organization',
    method: 'GET',
    resourceId: '/common/organization/get-current-organization',
    extraOptions: {},
    resourceType: 'Organization',
    resourceCode: 'organization__get_current',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'Organization Product Subscription List',
    method: 'GET',
    resourceId: '/common/product-subscription/list',
    extraOptions: {},
    resourceType: 'Product Subscription',
    resourceCode: 'productSubscription__list',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'Get Entities List',
    method: 'GET',
    resourceId: '/common/entities/list',
    extraOptions: {},
    resourceType: 'Entities',
    resourceCode: 'entities__list',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'Get Entity Details',
    method: 'GET',
    resourceId: '/common/entities/:entityId',
    extraOptions: {},
    resourceType: 'Entities',
    resourceCode: 'entities__get',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'Update Entity Details',
    method: 'PUT',
    resourceId: '/common/entities/update/:entityId',
    extraOptions: {},
    resourceType: 'Entities',
    resourceCode: 'entities__update',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'Create Entity',
    method: 'POST',
    resourceId: '/common/entities/create',
    extraOptions: {},
    resourceType: 'Entities',
    resourceCode: 'entities__create',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'Check Data Source Code Availability',
    method: 'GET',
    resourceId: '/common/dataSource/code/:code',
    extraOptions: {},
    resourceType: 'Data Source',
    resourceCode: 'dataSource__check_code',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'Check Data Source Name Availability',
    method: 'GET',
    resourceId: '/common/dataSource/name/:name',
    extraOptions: {},
    resourceType: 'Data Source',
    resourceCode: 'dataSource__check_name',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'Create Data Source',
    method: 'POST',
    resourceId: '/common/dataSource/create',
    extraOptions: {},
    resourceType: 'Data Source',
    resourceCode: 'dataSource__create',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'Update Data Source',
    method: 'PUT',
    resourceId: '/common/dataSource/update/:dataSourceId',
    extraOptions: {},
    resourceType: 'Data Source',
    resourceCode: 'dataSource__update',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'List Data Sources',
    method: 'GET',
    resourceId: '/common/dataSource/list',
    extraOptions: {},
    resourceType: 'Data Source',
    resourceCode: 'dataSource__list',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'Get Data Source By ID',
    method: 'GET',
    resourceId: '/common/dataSource/dataSourceId/:dataSourceId',
    extraOptions: {},
    resourceType: 'Data Source',
    resourceCode: 'dataSource__get',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'Get Widget Data By Filter',
    method: 'POST',
    resourceId: '/common/dataSource/getWidgetDataByFilter',
    extraOptions: {},
    resourceType: 'Data Source',
    resourceCode: 'dataSource__get_widget_data',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'Export Widget Data By Filter',
    method: 'POST',
    resourceId: '/common/dataSource/getWidgetDataByFilter/export',
    extraOptions: {},
    resourceType: 'Data Source',
    resourceCode: 'dataSource__export_widget_data',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'Create Attribute Option',
    method: 'POST',
    resourceId: '/common/attributeOptions/create',
    extraOptions: {},
    resourceType: 'Attribute Option',
    resourceCode: 'attributeOption__create',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'Update Attribute Option',
    method: 'PUT',
    resourceId: '/common/attributeOptions/update/:attributeId',
    extraOptions: {},
    resourceType: 'Attribute Option',
    resourceCode: 'attributeOption__update',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'List Attribute Options',
    method: 'GET',
    resourceId: '/common/attributeOptions/list',
    extraOptions: {},
    resourceType: 'Attribute Option',
    resourceCode: 'attributeOption__list',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'Get Attribute Option By ID',
    method: 'GET',
    resourceId: '/common/attributeOptions/get/:attributeId',
    extraOptions: {},
    resourceType: 'Attribute Option',
    resourceCode: 'attributeOption__get',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'File Upload',
    method: 'POST',
    resourceId: '/common/files/upload',
    extraOptions: {},
    resourceType: 'File Upload',
    resourceCode: 'fileUpload__upload',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'List Data Source Versions',
    method: 'GET',
    resourceId: '/common/dataSourceVersion/list',
    extraOptions: {},
    resourceType: 'Data Source Version',
    resourceCode: 'dataSourceVersion__list',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'Check Data Source Version Name Availability',
    method: 'GET',
    resourceId:
      '/common/dataSourceVersion/dataSourceId/:dataSourceId/versionValue/:versionValue/versionName/:versionName',
    extraOptions: {},
    resourceType: 'Data Source Version',
    resourceCode: 'dataSourceVersion__check_name',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'Create or Update Data Source Version Value',
    method: 'POST',
    resourceId: '/common/dataSourceVersion/create',
    extraOptions: {},
    resourceType: 'Data Source Version',
    resourceCode: 'dataSourceVersion__create_update',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'Get Data Source Version Data by Data Source and Version Value',
    method: 'GET',
    resourceId: '/common/dataSourceVersion/versionData',
    extraOptions: {},
    resourceType: 'Data Source Version',
    resourceCode: 'dataSourceVersion__get_data',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'Export Data Source Version Data by Data Source and Version Value',
    method: 'GET',
    resourceId: '/common/dataSourceVersion/versionData/export',
    extraOptions: {},
    resourceType: 'Data Source Version',
    resourceCode: 'dataSourceVersion__export_data',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'Create Data Source Version Value',
    method: 'POST',
    resourceId: '/common/dataSourceVersion/versionData/create',
    extraOptions: {},
    resourceType: 'Data Source Version',
    resourceCode: 'dataSourceVersion_create_data',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'Update Data Source Version Value',
    method: 'PUT',
    resourceId: '/common/dataSourceVersion/versionData/update/:rowId',
    extraOptions: {},
    resourceType: 'Data Source Version',
    resourceCode: 'dataSourceVersion_update_data',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'Delete Data Source Version Value',
    method: 'DELETE',
    resourceId: '/common/dataSourceVersion/versionData/delete',
    extraOptions: {},
    resourceType: 'Data Source Version',
    resourceCode: 'dataSourceVersion_delete_data',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'Get Latest Data Source Version Detail by Custom Report ID',
    method: 'GET',
    resourceId: '/common/dataSourceVersion/listVersionData/:customReportId',
    extraOptions: {},
    resourceType: 'Data Source Version',
    resourceCode: 'dataSourceVersion__get_latest_detail',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'List All Available Data Source Version Values',
    method: 'GET',
    resourceId: '/common/dataSourceVersion/listAllAvailableDataSourceVersionValue',
    extraOptions: {},
    resourceType: 'Data Source Version',
    resourceCode: 'dataSourceVersion__list_all_available',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'Get Chart Data',
    method: 'POST',
    resourceId: '/common/dataSourceVersion/chartData',
    extraOptions: {},
    resourceType: 'Data Source Version',
    resourceCode: 'dataSourceVersion__get_chart_data',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'List Data Import Errors',
    method: 'GET',
    resourceId: '/common/dataImportError/list',
    extraOptions: {},
    resourceType: 'Data Source Version',
    resourceCode: 'dataSourceVersion__list_import_errors',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'List Dashboards',
    method: 'GET',
    resourceId: '/common/dashboard/list',
    extraOptions: {},
    resourceType: 'Dashboard',
    resourceCode: 'dashboard__list',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'Get Dashboard By ID',
    method: 'GET',
    resourceId: '/common/dashboard/get/:dashboardId',
    extraOptions: {},
    resourceType: 'Dashboard',
    resourceCode: 'dashboard__get',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'Create Dashboard',
    method: 'POST',
    resourceId: '/common/dashboard/create',
    extraOptions: {},
    resourceType: 'Dashboard',
    resourceCode: 'dashboard__create',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'Update Dashboard',
    method: 'POST',
    resourceId: '/common/dashboard/update/:dashboardId',
    extraOptions: {},
    resourceType: 'Dashboard',
    resourceCode: 'dashboard__update',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'Delete Dashboard',
    method: 'POST',
    resourceId: '/common/dashboard/delete/:dashboardId',
    extraOptions: {},
    resourceType: 'Dashboard',
    resourceCode: 'dashboard__delete',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'Select Dashboard Theme',
    method: 'POST',
    resourceId: '/common/dashboard/selectTheme/:dashboardId',
    extraOptions: {},
    resourceType: 'Dashboard',
    resourceCode: 'dashboard__select_theme',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'Get Dashboard Widgets',
    method: 'GET',
    resourceId: '/common/dashboard/widget/getWidgets/:dashboardId',
    extraOptions: {},
    resourceType: 'Dashboard',
    resourceCode: 'dashboard__get_widgets',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'Get Widget Data',
    method: 'POST',
    resourceId: '/common/dashboard/widget/getWidgetData',
    extraOptions: {},
    resourceType: 'Dashboard',
    resourceCode: 'dashboard__get_widget_data',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'Get Widget Plot Types',
    method: 'GET',
    resourceId: '/common/dashboard/widget/getPlotTypes',
    extraOptions: {},
    resourceType: 'Dashboard',
    resourceCode: 'dashboard__get_widget_plot_types',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'Create Widget',
    method: 'POST',
    resourceId: '/common/dashboard/widget/create',
    extraOptions: {},
    resourceType: 'Dashboard',
    resourceCode: 'dashboard__create_widget',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'Save Dashboard Widgets',
    method: 'POST',
    resourceId: '/common/dashboard/widget/save',
    extraOptions: {},
    resourceType: 'Dashboard',
    resourceCode: 'dashboard__save_widgets',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'Update Widget',
    method: 'POST',
    resourceId: '/common/dashboard/widget/update/:dashboardWidgetId',
    extraOptions: {},
    resourceType: 'Dashboard',
    resourceCode: 'dashboard__update_widget',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'Delete Widget',
    method: 'POST',
    resourceId: '/common/dashboard/widget/delete/:dashboardWidgetId',
    extraOptions: {},
    resourceType: 'Dashboard',
    resourceCode: 'dashboard__delete_widget',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'Create Widget Type',
    method: 'POST',
    resourceId: '/common/widgetType/create',
    extraOptions: {},
    resourceType: 'Widget Type',
    resourceCode: 'widgetType__create',
    isSuperUser: true,
    isChangeable: true,
  },
  {
    name: 'Update Widget Type',
    method: 'POST',
    resourceId: '/common/widgetType/update/:widgetTypeId',
    extraOptions: {},
    resourceType: 'Widget Type',
    resourceCode: 'widgetType__update',
    isSuperUser: true,
    isChangeable: true,
  },
  {
    name: 'Delete Widget Type',
    method: 'POST',
    resourceId: '/common/widgetType/delete/:widgetTypeId',
    extraOptions: {},
    resourceType: 'Widget Type',
    resourceCode: 'widgetType__delete',
    isSuperUser: true,
    isChangeable: true,
  },
  {
    name: 'Get Widget Type By ID',
    method: 'GET',
    resourceId: '/common/widgetType/get/:widgetTypeId',
    extraOptions: {},
    resourceType: 'Widget Type',
    resourceCode: 'widgetType__get',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'List Widget Types',
    method: 'GET',
    resourceId: '/common/widgetType/list',
    extraOptions: {},
    resourceType: 'Widget Type',
    resourceCode: 'widgetType__list',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'Get Operator By ID',
    method: 'GET',
    resourceId: '/common/operator/get/:operatorId',
    extraOptions: {},
    resourceType: 'Operator',
    resourceCode: 'operator__get',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'List Operators',
    method: 'POST',
    resourceId: '/common/operator/list',
    extraOptions: {},
    resourceType: 'Operator',
    resourceCode: 'operator__list',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'Update Operator',
    method: 'POST',
    resourceId: '/common/operator/update/:operatorId',
    extraOptions: {},
    resourceType: 'Operator',
    resourceCode: 'operator__update',
    isSuperUser: true,
    isChangeable: true
  },
  {
    name: 'Create Operator',
    method: 'POST',
    resourceId: '/common/operator/create',
    extraOptions: {},
    resourceType: 'Operator',
    resourceCode: 'operator__create',
    isSuperUser: true,
    isChangeable: true
  },
  {
    name: 'List Widget Themes',
    method: 'GET',
    resourceId: '/common/widgetTheme/list',
    extraOptions: {},
    resourceType: 'get_data_by_version_idWidget Theme',
    resourceCode: 'widgetTheme__list',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'Get Widget Theme By ID',
    method: 'GET',
    resourceId: '/common/widgetTheme/:widgetThemeId',
    extraOptions: {},
    resourceType: 'Widget Theme',
    resourceCode: 'widgetTheme__get',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'Create Widget Theme',
    method: 'POST',
    resourceId: '/common/widgetTheme/create',
    extraOptions: {},
    resourceType: 'Widget Theme',
    resourceCode: 'widgetTheme__create',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'Duplicate Widget Theme',
    method: 'POST',
    resourceId: '/common/widgetTheme/duplicate/:widgetThemeId',
    extraOptions: {},
    resourceType: 'Widget Theme',
    resourceCode: 'widgetTheme__duplicate',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'Update Widget Theme',
    method: 'POST',
    resourceId: '/common/widgetTheme/update/:widgetThemeId',
    extraOptions: {},
    resourceType: 'Widget Theme',
    resourceCode: 'widgetTheme__update',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'Delete Widget Theme',
    method: 'POST',
    resourceId: '/common/widgetTheme/delete/:widgetThemeId',
    extraOptions: {},
    resourceType: 'Widget Theme',
    resourceCode: 'widgetTheme__delete',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'List Dashboard Shares',
    method: 'GET',
    resourceId: '/common/dashboardShare/list/:dashboardId',
    extraOptions: {},
    resourceType: 'Dashboard Share',
    resourceCode: 'dashboardShare__list',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'Create Dashboard Share',
    method: 'POST',
    resourceId: '/common/dashboardShare/create',
    extraOptions: {},
    resourceType: 'Dashboard Share',
    resourceCode: 'dashboardShare__create',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'Delete Dashboard Share',
    method: 'POST',
    resourceId: '/common/dashboardShare/:dashboardShareId',
    extraOptions: {},
    resourceType: 'Dashboard Share',
    resourceCode: 'dashboardShare__delete',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'List Custom Reports',
    method: 'GET',
    resourceId: '/reportivix/customReports/list',
    extraOptions: {},
    resourceType: 'Custom Report',
    resourceCode: 'customReport__list',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'List Report Requests',
    method: 'GET',
    resourceId: '/reportivix/customReports/listReportRequest',
    extraOptions: {},
    resourceType: 'Custom Report',
    resourceCode: 'customReport__list_requests',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'Get Report Version Values',
    method: 'GET',
    resourceId: '/reportivix/customReports/getVersionValue',
    extraOptions: {},
    resourceType: 'Custom Report',
    resourceCode: 'customReport__get_version_values',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'Generate Custom Report',
    method: 'POST',
    resourceId: '/reportivix/customReports/generate',
    extraOptions: {},
    resourceType: 'Custom Report',
    resourceCode: 'customReport__generate',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'Download Report',
    method: 'GET',
    resourceId: '/reportivix/customReports/downloadSupplementalIntermediate/:customReportId',
    extraOptions: {},
    resourceType: 'Custom Report',
    resourceCode: 'customReport__download_supplemental_intermediate',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'Download Supplemental Report',
    method: 'GET',
    resourceId: '/reportivix/customReports/download/:reportRequestId',
    extraOptions: {},
    resourceType: 'Custom Report',
    resourceCode: 'customReport__download',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'Get Report Data by Data Source Version ID',
    method: 'GET',
    resourceId: '/reportivix/customReports/reportDataOnDataSourceVersionId/:dataSourceVersionId',
    extraOptions: {},
    resourceType: 'Custom Report',
    resourceCode: 'customReport__get_data_by_version_id',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'Get Custom Report Design Details',
    method: 'GET',
    resourceId: '/reportivix/customReports/customReportDesignData/:customReportId',
    extraOptions: {},
    resourceType: 'Custom Report',
    resourceCode: 'customReport__get_design_details',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'Get Report Request Details',
    method: 'GET',
    resourceId: '/reportivix/customReports/reportDetails/:reportRequestId',
    extraOptions: {},
    resourceType: 'Custom Report',
    resourceCode: 'customReport__get_request_details',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'Get Custom Report Data by Data Source & Version Range',
    method: 'GET',
    resourceId: '/reportivix/customReports/reportData/:dataSourceId',
    extraOptions: {},
    resourceType: 'Custom Report',
    resourceCode: 'customReport__get_data_by_range',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'List Custom Report Settings',
    method: 'GET',
    resourceId: '/reportivix/customReports/listSettings',
    extraOptions: {},
    resourceType: 'Custom Report',
    resourceCode: 'customReport__list_settings',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'Update Custom Report Settings',
    method: 'POST',
    resourceId: '/reportivix/customReports/updateSettings/:customReportId',
    extraOptions: {},
    resourceType: 'Custom Report',
    resourceCode: 'customReport__update_settings',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'Run Natural Language Query',
    method: 'GET',
    resourceId: '/reportivix/nlQuery/getData',
    extraOptions: {},
    resourceType: 'NL Query',
    resourceCode: 'nlQuery__get_data',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'Run Natural Language Insights',
    method: 'GET',
    resourceId: '/reportivix/nlQuery/insights',
    extraOptions: {},
    resourceType: 'NL Query',
    resourceCode: 'nlQuery__insights',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'Create Derived Field',
    method: 'POST',
    resourceId: '/common/derivedField/create',
    extraOptions: {},
    resourceType: 'Derived Field',
    resourceCode: 'derived_field__create',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'Update Derived Field',
    method: 'PUT',
    resourceId: '/common/derivedField/update/:id',
    extraOptions: {},
    resourceType: 'Derived Field',
    resourceCode: 'derived_field__update',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'Delete Derived Field',
    method: 'DELETE',
    resourceId: '/common/derivedField/delete/:id',
    extraOptions: {},
    resourceType: 'Derived Field',
    resourceCode: 'derived_field__delete',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'List Derived Fields',
    method: 'GET',
    resourceId: '/common/derivedField/list',
    extraOptions: {},
    resourceType: 'Derived Field',
    resourceCode: 'derived_field__list',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'Get Derived Field',
    method: 'GET',
    resourceId: '/common/derivedField/:id',
    extraOptions: {},
    resourceType: 'Derived Field',
    resourceCode: 'derived_field__get',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'List Notification Types',
    method: 'GET',
    resourceId: '/notivix/notification-setting/type/list',
    extraOptions: {},
    resourceType: 'Notification Setting Type',
    resourceCode: 'notification_setting_type__list',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'Create Notification Type',
    method: 'POST',
    resourceId: '/notivix/notification-setting/type/create',
    extraOptions: {},
    resourceType: 'Notification Setting Type',
    resourceCode: 'notification_setting_type__create',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'Update Notification Type',
    method: 'PUT',
    resourceId: '/notivix/notification-setting/type/update/:id',
    extraOptions: {},
    resourceType: 'Notification Setting Type',
    resourceCode: 'notification_setting_type__update',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'Delete Notification Type',
    method: 'DELETE',
    resourceId: '/notivix/notification-setting/type/delete/:id',
    extraOptions: {},
    resourceType: 'Notification Setting Type',
    resourceCode: 'notification_setting_type__delete',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'Summary Notification Type',
    method: 'POST',
    resourceId: '/notivix/notification-setting/type/summary',
    extraOptions: {},
    resourceType: 'Notification Setting Type',
    resourceCode: 'notification_setting_type__summary_create',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'Get Notification Type',
    method: 'GET',
    resourceId: '/notivix/notification-setting/type/:id',
    extraOptions: {},
    resourceType: 'Notification Setting Type',
    resourceCode: 'notification_setting_type__get',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'List Notification Frequencies',
    method: 'GET',
    resourceId: '/notivix/notification-setting/frequency/list',
    extraOptions: {},
    resourceType: 'Notification Setting Frequency',
    resourceCode: 'notification_setting_frequency__list',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'Create Notification Frequency',
    method: 'POST',
    resourceId: '/notivix/notification-setting/frequency/create',
    extraOptions: {},
    resourceType: 'Notification Setting Frequency',
    resourceCode: 'notification_setting_frequency__create',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'Update Notification Frequency',
    method: 'PUT',
    resourceId: '/notivix/notification-setting/frequency/update/:id',
    extraOptions: {},
    resourceType: 'Notification Setting Frequency',
    resourceCode: 'notification_setting_frequency__update',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'Delete Notification Frequency',
    method: 'DELETE',
    resourceId: '/notivix/notification-setting/frequency/delete/:id',
    extraOptions: {},
    resourceType: 'Notification Setting Frequency',
    resourceCode: 'notification_setting_frequency__delete',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'Get Notification Frequency',
    method: 'GET',
    resourceId: '/notivix/notification-setting/frequency/:id',
    extraOptions: {},
    resourceType: 'Notification Setting Frequency',
    resourceCode: 'notification_setting_frequency__get',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'List Notification Templates',
    method: 'GET',
    resourceId: '/notivix/notification-setting/template/list',
    extraOptions: {},
    resourceType: 'Notification Setting Template',
    resourceCode: 'notification_setting_template__list',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'Create Notification Template',
    method: 'POST',
    resourceId: '/notivix/notification-setting/template/create',
    extraOptions: {},
    resourceType: 'Notification Setting Template',
    resourceCode: 'notification_setting_template__create',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'Update Notification Template',
    method: 'PUT',
    resourceId: '/notivix/notification-setting/template/update/:id',
    extraOptions: {},
    resourceType: 'Notification Setting Template',
    resourceCode: 'notification_setting_template__update',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'Delete Notification Template',
    method: 'DELETE',
    resourceId: '/notivix/notification-setting/template/delete/:id',
    extraOptions: {},
    resourceType: 'Notification Setting Template',
    resourceCode: 'notification_setting_template__delete',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'Get Notification Template',
    method: 'GET',
    resourceId: '/notivix/notification-setting/template/:id',
    extraOptions: {},
    resourceType: 'Notification Setting Template',
    resourceCode: 'notification_setting_template__get',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'List Notification Medium Settings',
    method: 'GET',
    resourceId: '/notivix/notification-setting/medium/list',
    extraOptions: {},
    resourceType: 'Notification Medium Setting',
    resourceCode: 'notification_setting_medium__list',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'Create Notification Medium Setting',
    method: 'POST',
    resourceId: '/notivix/notification-setting/medium/create',
    extraOptions: {},
    resourceType: 'Notification Medium Setting',
    resourceCode: 'notification_setting_medium__create',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'Update Notification Medium Setting',
    method: 'PUT',
    resourceId: '/notivix/notification-setting/medium/update/:id',
    extraOptions: {},
    resourceType: 'Notification Medium Setting',
    resourceCode: 'notification_setting_medium__update',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'Delete Notification Medium Setting',
    method: 'DELETE',
    resourceId: '/notivix/notification-setting/medium/delete',
    extraOptions: {},
    resourceType: 'Notification Medium Setting',
    resourceCode: 'notification_setting_medium__delete',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'Get Notification Medium',
    method: 'GET',
    resourceId: '/notivix/notification-setting/medium/:id',
    extraOptions: {},
    resourceType: 'Notification Medium Setting',
    resourceCode: 'notification_setting_medium__get',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'Trigger Notification Prepared',
    method: 'POST',
    resourceId: '/notivix/notification-setting/prepared/trigger',
    extraOptions: {},
    resourceType: 'Notification Prepared',
    resourceCode: 'notification_prepared_trigger__create',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'List Notification Prepared',
    method: 'GET',
    resourceId: '/notivix/notification-setting/prepared/notification/list',
    extraOptions: {},
    resourceType: 'Notification Prepared',
    resourceCode: 'notification_prepared__list',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'Resend Notification Prepared',
    method: 'POST',
    resourceId: '/notivix/notification-setting/prepared/notification/resend',
    extraOptions: {},
    resourceType: 'Notification Prepared',
    resourceCode: 'notification_prepared_resend__create',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'List Dashboard Font Themes',
    method: 'GET',
    resourceId: '/common/dashboardFont/list',
    extraOptions: {},
    resourceType: 'Dashboard Font Theme',
    resourceCode: 'dashboard_font_theme__list',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'Download Dashboard Font Theme',
    method: 'GET',
    resourceId: '/common/dashboardFont/download/:fontId',
    extraOptions: {},
    resourceType: 'Dashboard Font Theme',
    resourceCode: 'dashboard_font_theme__download',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'Delete Dashboard Font Theme',
    method: 'DELETE',
    resourceId: '/common/dashboardFont/delete/:fontId',
    extraOptions: {},
    resourceType: 'Dashboard Font Theme',
    resourceCode: 'dashboard_font_theme__delete',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'List Dashboard Themes',
    method: 'GET',
    resourceId: '/common/dashboardTheme/list',
    extraOptions: {},
    resourceType: 'Dashboard Theme',
    resourceCode: 'dashboard_theme__list',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'Create Dashboard Theme',
    method: 'POST',
    resourceId: '/common/dashboardTheme/create',
    extraOptions: {},
    resourceType: 'Dashboard Theme',
    resourceCode: 'dashboard_theme__create',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'Update Dashboard Theme',
    method: 'PUT',
    resourceId: '/common/dashboardTheme/update/:themeId',
    extraOptions: {},
    resourceType: 'Dashboard Theme',
    resourceCode: 'dashboard_theme__update',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'Delete Dashboard Theme',
    method: 'DELETE',
    resourceId: '/common/dashboardTheme/delete/:themeId',
    extraOptions: {},
    resourceType: 'Dashboard Theme',
    resourceCode: 'dashboard_theme__delete',
    isSuperUser: false,
    isChangeable: true,
  },
  // GET current user profile image
  {
    name: 'Get Current User Profile Image',
    method: 'GET',
    resourceId: '/common/user/image',
    extraOptions: {},
    resourceType: 'User Profile Image',
    resourceCode: 'user_profile_image__get',
    isSuperUser: false,
    isChangeable: true,
  },

  // DELETE current user profile image
  {
    name: 'Delete Current User Profile Image',
    method: 'DELETE',
    resourceId: '/common/user/image',
    extraOptions: {},
    resourceType: 'User Profile Image',
    resourceCode: 'user_profile_image__delete',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'Create Department',
    method: 'POST',
    resourceId: '/common/department/create',
    extraOptions: {},
    resourceType: 'Department',
    resourceCode: 'department__create',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'Update Department',
    method: 'PUT',
    resourceId: '/common/department/update/:departmentId',
    extraOptions: {},
    resourceType: 'Department',
    resourceCode: 'department__update',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'List Departments',
    method: 'GET',
    resourceId: '/common/department/list',
    extraOptions: {},
    resourceType: 'Department',
    resourceCode: 'department__list',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'Delete Department',
    method: 'DELETE',
    resourceId: '/common/department/delete/:departmentId',
    extraOptions: {},
    resourceType: 'Department',
    resourceCode: 'department__delete',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'Create Designation',
    method: 'POST',
    resourceId: '/common/designation/create',
    extraOptions: {},
    resourceType: 'Designation',
    resourceCode: 'designation__create',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'Update Designation',
    method: 'PUT',
    resourceId: '/common/designation/update/:designationId',
    extraOptions: {},
    resourceType: 'Designation',
    resourceCode: 'designation__update',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'List Designations',
    method: 'GET',
    resourceId: '/common/designation/list',
    extraOptions: {},
    resourceType: 'Designation',
    resourceCode: 'designation__list',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'Delete Designation',
    method: 'GET',
    resourceId: '/common/designation/delete/:designationId',
    extraOptions: {},
    resourceType: 'Designation',
    resourceCode: 'designation__delete',
    isSuperUser: false,
    isChangeable: true,
  },
  {
  name: 'Create User Data Permission',
  method: 'POST',
  resourceId: '/common/user-data-permission/create',
  extraOptions: {},
  resourceType: 'UserDataPermission',
  resourceCode: 'userDataPermission__create',
  isSuperUser: false,
  isChangeable: true,
},
{
  name: 'Update User Data Permission',
  method: 'PUT',
  resourceId: '/common/user-data-permission/update/:id',
  extraOptions: {},
  resourceType: 'UserDataPermission',
  resourceCode: 'userDataPermission__update',
  isSuperUser: false,
  isChangeable: true,
},
{
  name: 'Delete User Data Permission',
  method: 'DELETE',
  resourceId: '/common/user-data-permission/delete/:id',
  extraOptions: {},
  resourceType: 'UserDataPermission',
  resourceCode: 'userDataPermission__delete',
  isSuperUser: false,
  isChangeable: true,
},
{
  name: 'List User Data Permissions',
  method: 'GET',
  resourceId: '/common/user-data-permission/list',
  extraOptions: {},
  resourceType: 'UserDataPermission',
  resourceCode: 'userDataPermission__list',
  isSuperUser: false,
  isChangeable: true,
},
{
  name: 'Get User Data Permission',
  method: 'GET',
  resourceId: '/common/user-data-permission/:id',
  extraOptions: {},
  resourceType: 'UserDataPermission',
  resourceCode: 'userDataPermission__get',
  isSuperUser: false,
  isChangeable: true,
},
{
    name: 'List Download Requests',
    method: 'GET',
    resourceId: '/common/download-request/list',
    extraOptions: {},
    resourceType: 'DownloadRequest',
    resourceCode: 'downloadRequest__list',
    isSuperUser: false,
    isChangeable: true,
  },
  {
    name: 'Download File',
    method: 'GET',
    resourceId: '/common/download-request/download/:id',
    extraOptions: {},
    resourceType: 'DownloadRequest',
    resourceCode: 'downloadRequest__download',
    isSuperUser: false,
    isChangeable: true,
  }
];

export async function seedPermissions(permissionList: any[]) {
  const dynamicPermission = await getDynamicPermission(permissionList);
  console.log(dynamicPermission);
  permissions = [...permissions, ...dynamicPermission];

  // 🔹 Define method → methodName mapping
  const methodNameArr: Record<string, string> = {
    POST: 'create',
    PUT: 'update',
    DELETE: 'delete',
    GET: 'list',
  };

  for (const perm of permissions) {
    const { resourceCode } = perm;

    const query: any = { resourceCode };

    if (perm.organizationId) {
      query.organizationId = perm.organizationId;
    }

    const existing = await Permission.findOne(query);


    if (!existing) {
      const methodName = methodNameArr[perm.method?.toUpperCase()] || 'UNKNOWN';

      const newPermission = new Permission({
        ...perm,
        status: 'active',
        methodName,
        extraOptions: perm.extraOptions || {},
      });

      await newPermission.save();
      console.info(`✅ Permission "${perm.name}" created.`);
    } else {
      console.info(`ℹ️ Permission "${perm.name}" already exists.`);
    }
  }
}

