import Permission from '../database/models/common/permissionModel'; // Your Mongoose model

const permissions = [
  { name: 'List User', method: 'GET', resourceId: '/common/user/list', extraOptions: {}, resourceType: 'User' },
  {
    name: 'Get Current User',
    method: 'GET',
    resourceId: '/common/user/get-current-user',
    extraOptions: {},
    resourceType: 'User',
    isSuperUser: false,
  },
  { name: 'Get User', method: 'GET', resourceId: '/common/user/:userId', resourceType: 'User', isSuperUser: false },
  {
    name: 'Create User',
    method: 'POST',
    resourceId: '/common/user/create',
    extraOptions: {},
    resourceType: 'User',
    isSuperUser: false,
  },
  {
    name: 'Update Current User',
    method: 'PUT',
    resourceId: '/common/user/update-current-user',
    extraOptions: {},
    resourceType: 'User',
    isSuperUser: false,
  },
  {
    name: 'Update Current User Password',
    method: 'PUT',
    resourceId: '/common/user/change-password',
    extraOptions: {},
    resourceType: 'User',
    isSuperUser: false,
  },
  {
    name: 'Update User',
    method: 'PUT',
    resourceId: '/common/user/update/:userId',
    extraOptions: {},
    resourceType: 'User',
    isSuperUser: false,
  },
  {
    name: 'Delete User',
    method: 'DELETE',
    resourceId: '/common/user/delete/:userId',
    extraOptions: {},
    resourceType: 'User',
    isSuperUser: false,
  },
  {
    name: 'List Permission',
    method: 'GET',
    resourceId: '/common/permission/list',
    extraOptions: {},
    resourceType: 'Permission',
    isSuperUser: false,
  },
  {
    name: 'Create Permission',
    method: 'POST',
    resourceId: '/common/permission/create',
    extraOptions: {},
    resourceType: 'Permission',
    isSuperUser: false,
  },
  {
    name: 'Update Permission',
    method: 'PUT',
    resourceId: '/common/permission/update/:permissionId',
    extraOptions: {},
    resourceType: 'Permission',
    isSuperUser: false,
  },
  {
    name: 'Delete Permission',
    method: 'DELETE',
    resourceId: '/common/permission/delete/:permissionId',
    extraOptions: {},
    resourceType: 'Permission',
    isSuperUser: false,
  },
  {
    name: 'List Role',
    method: 'GET',
    resourceId: '/common/role/list',
    extraOptions: {},
    resourceType: 'Role',
    isSuperUser: false,
  },
  {
    name: 'List Role Permission',
    method: 'GET',
    resourceId: '/common/role/:roleId',
    extraOptions: {},
    resourceType: 'Role',
    isSuperUser: false,
  },
  {
    name: 'Create Role',
    method: 'POST',
    resourceId: '/common/role/create',
    extraOptions: {},
    resourceType: 'Role',
    isSuperUser: false,
  },
  {
    name: 'Update Role',
    method: 'PUT',
    resourceId: '/common/role/update/:roleId',
    extraOptions: {},
    resourceType: 'Role',
    isSuperUser: false,
  },
  {
    name: 'Delete Role',
    method: 'DELETE',
    resourceId: '/common/role/delete/:roleId',
    extraOptions: {},
    resourceType: 'Role',
    isSuperUser: false,
  },
  {
    name: 'Product List',
    method: 'GET',
    resourceId: '/common/product/list',
    extraOptions: {},
    resourceType: 'Product',
    isSuperUser: true,
  },
  {
    name: 'Create Organization',
    method: 'POST',
    resourceId: '/common/organization/create',
    extraOptions: {},
    resourceType: 'Organization',
    isSuperUser: true,
  },
  {
    name: 'Update Organization',
    method: 'PUT',
    resourceId: '/common/organization/update/:organizationId',
    extraOptions: {},
    resourceType: 'Organization',
    isSuperUser: true,
  },
  {
    name: 'Delete Organization',
    method: 'DELETE',
    resourceId: '/common/organization/delete/:organizationId',
    extraOptions: {},
    resourceType: 'Organization',
    isSuperUser: true,
  },
  {
    name: 'Organization List',
    method: 'GET',
    resourceId: '/common/organization/list',
    extraOptions: {},
    resourceType: 'Organization',
    isSuperUser: true,
  },
  {
    name: 'Get Organization',
    method: 'GET',
    resourceId: '/common/organization/:organizationId',
    extraOptions: {},
    resourceType: 'Organization',
    isSuperUser: true,
  },
  {
    name: 'Get Current Organization',
    method: 'GET',
    resourceId: '/common/organization/get-current-organization',
    extraOptions: {},
    resourceType: 'Organization',
    isSuperUser: false,
  },
  {
    name: 'Organization Product Subscription List',
    method: 'GET',
    resourceId: '/common/product-subscription/list',
    extraOptions: {},
    resourceType: 'Product Subscription',
    isSuperUser: true,
  },
  {
    name: 'Get Entities List',
    method: 'GET',
    resourceId: '/common/entities/list',
    extraOptions: {},
    resourceType: 'Entities',
    isSuperUser: false,
  },
  {
    name: 'Get Entity Details',
    method: 'GET',
    resourceId: '/common/entities/:entityId',
    extraOptions: {},
    resourceType: 'Entities',
    isSuperUser: false,
  },
  {
    name: 'Update Entity Details',
    method: 'PUT',
    resourceId: '/common/entities/update/:entityId',
    extraOptions: {},
    resourceType: 'Entities',
    isSuperUser: false,
  },
  {
    name: 'Create Entity',
    method: 'POST',
    resourceId: '/common/entities/create',
    extraOptions: {},
    resourceType: 'Entities',
    isSuperUser: false,
  },
  {
    name: 'Check Data Source Code Availability',
    method: 'GET',
    resourceId: '/common/dataSource/code/:code',
    extraOptions: {},
    resourceType: 'Data Source Static',
    isSuperUser: false,
  },
  {
    name: 'Check Data Source Name Availability',
    method: 'GET',
    resourceId: '/common/dataSource/name/:name',
    extraOptions: {},
    resourceType: 'Data Source Static',
    isSuperUser: false,
  },
  {
    name: 'Create Data Source',
    method: 'POST',
    resourceId: '/common/dataSource/create',
    extraOptions: {},
    resourceType: 'Data Source Static',
    isSuperUser: false,
  },
  {
    name: 'Update Data Source',
    method: 'PUT',
    resourceId: '/common/dataSource/update/:dataSourceId',
    extraOptions: {},
    resourceType: 'Data Source Static',
    isSuperUser: false,
  },
  {
    name: 'List Data Sources',
    method: 'GET',
    resourceId: '/common/dataSource/list',
    extraOptions: {},
    resourceType: 'Data Source Static',
    isSuperUser: false,
  },
  {
    name: 'Get Data Source By ID',
    method: 'GET',
    resourceId: '/common/dataSource/dataSourceId/:dataSourceId',
    extraOptions: {},
    resourceType: 'Data Source Static',
    isSuperUser: false,
  },
  {
    name: 'Get Widget Data By Filter',
    method: 'POST',
    resourceId: '/common/dataSource/getWidgetDataByFilter',
    extraOptions: {},
    resourceType: 'Data Source Static',
    isSuperUser: false,
  },
  {
    name: 'Create Attribute Option',
    method: 'POST',
    resourceId: '/common/attributeOptions/create',
    extraOptions: {},
    resourceType: 'Attribute Option',
    isSuperUser: false,
  },
  {
    name: 'Update Attribute Option',
    method: 'PUT',
    resourceId: '/common/attributeOptions/update/:attributeId',
    extraOptions: {},
    resourceType: 'Attribute Option',
    isSuperUser: false,
  },
  {
    name: 'List Attribute Options',
    method: 'GET',
    resourceId: '/common/attributeOptions/list',
    extraOptions: {},
    resourceType: 'Attribute Option',
    isSuperUser: false,
  },
  {
    name: 'Get Attribute Option By ID',
    method: 'GET',
    resourceId: '/common/attributeOptions/get/:attributeId',
    extraOptions: {},
    resourceType: 'Attribute Option',
    isSuperUser: false,
  },
  {
    name: 'File Upload',
    method: 'POST',
    resourceId: '/common/files/upload',
    extraOptions: {},
    resourceType: 'File Upload',
    isSuperUser: false,
  },
  {
    name: 'List Data Source Versions',
    method: 'GET',
    resourceId: '/common/dataSourceVersion/list',
    extraOptions: {},
    resourceType: 'Data Source Version',
    isSuperUser: false,
  },
  {
    name: 'Check Data Source Version Name Availability',
    method: 'GET',
    resourceId:
      '/common/dataSourceVersion/dataSourceId/:dataSourceId/versionValue/:versionValue/versionName/:versionName',
    extraOptions: {},
    resourceType: 'Data Source Version',
    isSuperUser: false,
  },
  {
    name: 'Create or Update Data Source Version Value',
    method: 'POST',
    resourceId: '/common/dataSourceVersion/create',
    extraOptions: {},
    resourceType: 'Data Source Version',
    isSuperUser: false,
  },
  {
    name: 'Get Data Source Version Data by Data Source and Version Value',
    method: 'GET',
    resourceId: '/common/dataSourceVersion/versionData',
    extraOptions: {},
    resourceType: 'Data Source Version',
    isSuperUser: false,
  },
  {
    name: 'Get Latest Data Source Version Detail by Custom Report ID',
    method: 'GET',
    resourceId: '/common/dataSourceVersion/listVersionData/:customReportId',
    extraOptions: {},
    resourceType: 'Data Source Version',
    isSuperUser: false,
  },
  {
    name: 'List All Available Data Source Version Values',
    method: 'GET',
    resourceId: '/common/dataSourceVersion/listAllAvailableDataSourceVersionValue',
    extraOptions: {},
    resourceType: 'Data Source Version',
    isSuperUser: false,
  },
  {
    name: 'List Data Import Errors',
    method: 'GET',
    resourceId: '/common/dataImportError/list',
    extraOptions: {},
    resourceType: 'Data Source Version',
    isSuperUser: false,
  },
  {
    name: 'List Dashboards',
    method: 'GET',
    resourceId: '/common/dashboard/list',
    extraOptions: {},
    resourceType: 'Dashboard',
    isSuperUser: false,
  },
  {
    name: 'Get Dashboard By ID',
    method: 'GET',
    resourceId: '/common/dashboard/get/:dashboardId',
    extraOptions: {},
    resourceType: 'Dashboard',
    isSuperUser: false,
  },
  {
    name: 'Create Dashboard',
    method: 'POST',
    resourceId: '/common/dashboard/create',
    extraOptions: {},
    resourceType: 'Dashboard',
    isSuperUser: false,
  },
  {
    name: 'Update Dashboard',
    method: 'POST',
    resourceId: '/common/dashboard/update/:dashboardId',
    extraOptions: {},
    resourceType: 'Dashboard',
    isSuperUser: false,
  },
  {
    name: 'Delete Dashboard',
    method: 'POST',
    resourceId: '/common/dashboard/delete/:dashboardId',
    extraOptions: {},
    resourceType: 'Dashboard',
    isSuperUser: false,
  },
  {
    name: 'Select Dashboard Theme',
    method: 'POST',
    resourceId: '/common/dashboard/selectTheme/:dashboardId',
    extraOptions: {},
    resourceType: 'Dashboard',
    isSuperUser: false,
  },
  // Dashboard Widget routes
  {
    name: 'Get Dashboard Widgets',
    method: 'GET',
    resourceId: '/common/dashboard/widget/getWidgets/:dashboardId',
    extraOptions: {},
    resourceType: 'Dashboard',
    isSuperUser: false,
  },
  {
    name: 'Get Widget Data',
    method: 'POST',
    resourceId: '/common/dashboard/widget/getWidgetData',
    extraOptions: {},
    resourceType: 'Dashboard',
    isSuperUser: false,
  },
  {
    name: 'Create Widget',
    method: 'POST',
    resourceId: '/common/dashboard/widget/create',
    extraOptions: {},
    resourceType: 'Dashboard',
    isSuperUser: false,
  },
  {
    name: 'Save Dashboard Widgets',
    method: 'POST',
    resourceId: '/common/dashboard/widget/save',
    extraOptions: {},
    resourceType: 'Dashboard',
    isSuperUser: false,
  },
  {
    name: 'Update Widget',
    method: 'POST',
    resourceId: '/common/dashboard/widget/update/:dashboardWidgetId',
    extraOptions: {},
    resourceType: 'Dashboard',
    isSuperUser: false,
  },
  {
    name: 'Delete Widget',
    method: 'POST',
    resourceId: '/common/dashboard/widget/delete/:dashboardWidgetId',
    extraOptions: {},
    resourceType: 'Dashboard',
    isSuperUser: false,
  },
  {
    name: 'Create Widget Type',
    method: 'POST',
    resourceId: '/common/widgetType/create',
    extraOptions: {},
    resourceType: 'Widget Type',
    isSuperUser: true,
  },
  {
    name: 'Update Widget Type',
    method: 'POST',
    resourceId: '/common/widgetType/update/:widgetTypeId',
    extraOptions: {},
    resourceType: 'Widget Type',
    isSuperUser: true,
  },
  {
    name: 'Delete Widget Type',
    method: 'POST',
    resourceId: '/common/widgetType/delete/:widgetTypeId',
    extraOptions: {},
    resourceType: 'Widget Type',
    isSuperUser: true,
  },
  {
    name: 'Get Widget Type By ID',
    method: 'GET',
    resourceId: '/common/widgetType/get/:widgetTypeId',
    extraOptions: {},
    resourceType: 'Widget Type',
    isSuperUser: false,
  },
  {
    name: 'List Widget Types',
    method: 'GET',
    resourceId: '/common/widgetType/list',
    extraOptions: {},
    resourceType: 'Widget Type',
    isSuperUser: false,
  },
  {
    name: 'Get Operator By ID',
    method: 'GET',
    resourceId: '/common/operator/get/:operatorId',
    extraOptions: {},
    resourceType: 'Operator',
    isSuperUser: false,
  },
  {
    name: 'List Operators',
    method: 'POST',
    resourceId: '/common/operator/list',
    extraOptions: {},
    resourceType: 'Operator',
    isSuperUser: false,
  },
  {
    name: 'Update Operator',
    method: 'POST',
    resourceId: '/common/operator/update/:operatorId',
    extraOptions: {},
    resourceType: 'Operator',
    isSuperUser: true,
  },
  {
    name: 'Create Operator',
    method: 'POST',
    resourceId: '/common/operator/create',
    extraOptions: {},
    resourceType: 'Operator',
    isSuperUser: true,
  },
  {
    name: 'List Widget Themes',
    method: 'GET',
    resourceId: '/common/widgetTheme/list',
    extraOptions: {},
    resourceType: 'Widget Theme',
    isSuperUser: false,
  },
  {
    name: 'Get Widget Theme By ID',
    method: 'GET',
    resourceId: '/common/widgetTheme/:widgetThemeId',
    extraOptions: {},
    resourceType: 'Widget Theme',
    isSuperUser: false,
  },
  {
    name: 'Create Widget Theme',
    method: 'POST',
    resourceId: '/common/widgetTheme/create',
    extraOptions: {},
    resourceType: 'Widget Theme',
    isSuperUser: false,
  },
  {
    name: 'Duplicate Widget Theme',
    method: 'POST',
    resourceId: '/common/widgetTheme/duplicate/:widgetThemeId',
    extraOptions: {},
    resourceType: 'Widget Theme',
    isSuperUser: false,
  },
  {
    name: 'Update Widget Theme',
    method: 'POST',
    resourceId: '/common/widgetTheme/update/:widgetThemeId',
    extraOptions: {},
    resourceType: 'Widget Theme',
    isSuperUser: false,
  },
  {
    name: 'Delete Widget Theme',
    method: 'POST',
    resourceId: '/common/widgetTheme/delete/:widgetThemeId',
    extraOptions: {},
    resourceType: 'Widget Theme',
    isSuperUser: false,
  },
  {
    name: 'List Dashboard Shares',
    method: 'GET',
    resourceId: '/common/dashboardShare/list/:dashboardId',
    extraOptions: {},
    resourceType: 'Dashboard Share',
    isSuperUser: false,
  },
  {
    name: 'Create Dashboard Share',
    method: 'POST',
    resourceId: '/common/dashboardShare/create',
    extraOptions: {},
    resourceType: 'Dashboard Share',
    isSuperUser: false,
  },
  {
    name: 'Delete Dashboard Share',
    method: 'POST',
    resourceId: '/common/dashboardShare/:dashboardShareId',
    extraOptions: {},
    resourceType: 'Dashboard Share',
    isSuperUser: false,
  },
  {
    name: 'List Custom Reports',
    method: 'GET',
    resourceId: '/reportivix/customReports/list',
    extraOptions: {},
    resourceType: 'Custom Report',
    isSuperUser: false,
  },
  {
    name: 'List Report Requests',
    method: 'GET',
    resourceId: '/reportivix/customReports/listReportRequest',
    extraOptions: {},
    resourceType: 'Custom Report',
    isSuperUser: false,
  },
  {
    name: 'Get Report Version Values',
    method: 'GET',
    resourceId: '/reportivix/customReports/getVersionValue',
    extraOptions: {},
    resourceType: 'Custom Report',
    isSuperUser: false,
  },
  {
    name: 'Generate Custom Report',
    method: 'POST',
    resourceId: '/reportivix/customReports/generate',
    extraOptions: {},
    resourceType: 'Custom Report',
    isSuperUser: false,
  },
  {
    name: 'Download Report',
    method: 'GET',
    resourceId: '/reportivix/customReports/download/:reportRequestId',
    extraOptions: {},
    resourceType: 'Custom Report',
    isSuperUser: false,
  },
  {
    name: 'Get Report Data by Data Source Version ID',
    method: 'GET',
    resourceId: '/reportivix/customReports/reportDataOnDataSourceVersionId/:dataSourceVersionId',
    extraOptions: {},
    resourceType: 'Custom Report',
    isSuperUser: false,
  },
  {
    name: 'Get Custom Report Design Details',
    method: 'GET',
    resourceId: '/reportivix/customReports/customReportDesignData/:customReportId',
    extraOptions: {},
    resourceType: 'Custom Report',
    isSuperUser: false,
  },
  {
    name: 'Get Report Request Details',
    method: 'GET',
    resourceId: '/reportivix/customReports/reportDetails/:reportRequestId',
    extraOptions: {},
    resourceType: 'Custom Report',
    isSuperUser: false,
  },
  {
    name: 'Get Custom Report Data by Data Source & Version Range',
    method: 'GET',
    resourceId: '/reportivix/customReports/reportData/:dataSourceId',
    extraOptions: {},
    resourceType: 'Custom Report',
    isSuperUser: false,
  },
  {
    name: 'List Custom Report Settings',
    method: 'GET',
    resourceId: '/reportivix/customReports/listSettings',
    extraOptions: {},
    resourceType: 'Custom Report',
    isSuperUser: false,
  },
  {
    name: 'Update Custom Report Settings',
    method: 'POST',
    resourceId: '/reportivix/customReports/updateSettings/:customReportId',
    extraOptions: {},
    resourceType: 'Custom Report',
    isSuperUser: false,
  },
  {
    name: 'Run Natural Language Aggregation',
    method: 'GET',
    resourceId: '/reportivix/nlQuery/getData',
    extraOptions: {},
    resourceType: 'NL Query',
    isSuperUser: false,
  },
  {
    name: 'Run Natural Language Insights',
    method: 'GET',
    resourceId: '/reportivix/nlQuery/insights',
    extraOptions: {},
    resourceType: 'NL Query',
    isSuperUser: false,
  },
];

export async function seedPermissions() {
  for (const perm of permissions) {
    const { method, resourceId } = perm;

    const existing = await Permission.findOne({ method, resourceId });

    if (!existing) {
      const newPermission = new Permission({
        ...perm,
        status: 'active',
        extraOptions: perm.extraOptions || {},
      });

      await newPermission.save();
      console.info(`✅ Permission "${perm.name}" created.`);
    } else {
      console.info(`ℹ️ Permission "${perm.name}" already exists.`);
    }
  }
}
